// Rice Village Shops - Business Listings Data
// All listings for the Rice Village area, Houston TX

const listings = [
  // ============================================
  // RESTAURANTS & DINING
  // ============================================
  { name: "Torchy's Tacos", category: "restaurant", subcategory: "Mexican", address: "2600 Travis St, Houston, TX 77006", description: "Austin-born taco chain serving creative, damn good tacos with signature queso and craft cocktails.", website: "https://www.torchystacos.com", phone: "(713) 595-8226", lat: 29.7180, lng: -95.4095 },
  { name: "Antonios Mexican Grille", category: "restaurant", subcategory: "Mexican", address: "2527 University Blvd, Houston, TX 77005", description: "Authentic Mexican cuisine with a modern twist in a warm, inviting atmosphere.", website: "https://www.antoniosmexicangrille.com", phone: "(713) 521-4288", lat: 29.7165, lng: -95.4110 },
  { name: "Azuma", category: "restaurant", subcategory: "Japanese", address: "5600 Kirby Dr, Houston, TX 77005", description: "Upscale Japanese sushi and robata grill with fresh, expertly prepared dishes.", website: "https://www.azumahouston.com", phone: "(713) 432-9649", lat: 29.7190, lng: -95.4120 },
  { name: "Black Walnut Cafe", category: "restaurant", subcategory: "American", address: "5510 Morningside Dr, Houston, TX 77005", description: "Modern American cafe serving creative breakfast, lunch, and brunch classics.", website: "https://www.blackwalnutcafe.com", phone: "(713) 526-5551", lat: 29.7155, lng: -95.4145 },
  { name: "Bronson's House", category: "restaurant", subcategory: "American", address: "2441 University Blvd, Houston, TX 77005", description: "Neighborhood spot offering hearty American comfort food and craft drinks.", website: "", phone: "", lat: 29.7162, lng: -95.4125 },
  { name: "Brown Bag Deli", category: "restaurant", subcategory: "Deli", address: "2523 Times Blvd, Houston, TX 77005", description: "Classic deli sandwiches and fresh-made soups in a casual setting.", website: "https://www.brownbagdeli.com", phone: "(713) 528-4001", lat: 29.7148, lng: -95.4118 },
  { name: "Buca di Beppo", category: "restaurant", subcategory: "Italian", address: "5192 Buffalo Speedway, Houston, TX 77005", description: "Family-style Italian restaurant with generous portions in a fun, eclectic setting.", website: "https://www.bucadibeppo.com", phone: "(713) 622-2822", lat: 29.7175, lng: -95.4180 },
  { name: "Cafe Rabelais", category: "restaurant", subcategory: "French", address: "2442 Times Blvd, Houston, TX 77005", description: "Charming French bistro offering classic cuisine, pastries, and an extensive wine list.", website: "https://www.caferabelais.com", phone: "(713) 520-8841", lat: 29.7150, lng: -95.4112 },
  { name: "Candelari's", category: "restaurant", subcategory: "Italian", address: "2506 Rice Blvd, Houston, TX 77005", description: "Neighborhood Italian spot with handmade pastas and wood-fired pizzas.", website: "https://www.candelaris.com", phone: "(713) 528-6440", lat: 29.7158, lng: -95.4102 },
  { name: "Chipotle Mexican Grill", category: "restaurant", subcategory: "Mexican", address: "2516 University Blvd, Houston, TX 77005", description: "Build-your-own burritos, bowls, and tacos with responsibly sourced ingredients.", website: "https://www.chipotle.com", phone: "(713) 522-2015", lat: 29.7168, lng: -95.4108 },
  { name: "CiCi's Pizza", category: "restaurant", subcategory: "Pizza", address: "2431 University Blvd, Houston, TX 77005", description: "All-you-can-eat pizza buffet with a wide variety of specialty pizzas and sides.", website: "https://www.cicis.com", phone: "(713) 521-2424", lat: 29.7160, lng: -95.4130 },
  { name: "Cochinita & Co.", category: "restaurant", subcategory: "Mexican", address: "2440 University Blvd, Houston, TX 77005", description: "Yucatecan-inspired street food featuring slow-roasted cochinita pibil.", website: "https://www.cochinitaandco.com", phone: "(832) 831-6291", lat: 29.7163, lng: -95.4115 },
  { name: "CoCo Crepes, Waffles & Coffee", category: "restaurant", subcategory: "Cafe", address: "2520 Rice Blvd, Houston, TX 77005", description: "Sweet and savory crepes, Belgian waffles, and specialty coffee drinks.", website: "https://www.cococrepes.com", phone: "(713) 521-5282", lat: 29.7156, lng: -95.4098 },
  { name: "Coppa Osteria", category: "restaurant", subcategory: "Italian", address: "5210 Morningside Dr, Houston, TX 77005", description: "Rustic Italian trattoria with handmade pasta, wood-fired dishes, and an inviting patio.", website: "https://www.coppaosteria.com", phone: "(713) 522-3535", lat: 29.7152, lng: -95.4148 },
  { name: "Cyclone Anaya's", category: "restaurant", subcategory: "Mexican", address: "5761 Woodway Dr, Houston, TX 77057", description: "Tex-Mex institution with signature enchiladas, margaritas, and lively atmosphere.", website: "https://www.cycloneanaya.com", phone: "(713) 520-6969", lat: 29.7195, lng: -95.4135 },
  { name: "D'Amico's Italian Market Cafe", category: "restaurant", subcategory: "Italian", address: "5510 Morningside Dr, Houston, TX 77005", description: "Casual Italian deli and cafe with imported goods, fresh pastas, and sandwiches.", website: "https://www.damicos-italian.com", phone: "(713) 526-3400", lat: 29.7154, lng: -95.4142 },
  { name: "Dave's Hot Chicken", category: "restaurant", subcategory: "American", address: "2540 University Blvd, Houston, TX 77005", description: "Nashville-style hot chicken tenders and sliders with customizable spice levels.", website: "https://www.daveshotchicken.com", phone: "(346) 331-8055", lat: 29.7170, lng: -95.4100 },
  { name: "El Meson", category: "restaurant", subcategory: "Cuban", address: "2425 University Blvd, Houston, TX 77005", description: "Vibrant Cuban restaurant with classic dishes, mojitos, and live music.", website: "https://www.elmesonhouston.com", phone: "(713) 526-4925", lat: 29.7158, lng: -95.4135 },
  { name: "El Topo", category: "restaurant", subcategory: "Mexican", address: "2437 University Blvd, Houston, TX 77005", description: "Modern Mexican cantina with elevated street food and creative cocktails.", website: "https://www.eltopohtx.com", phone: "(713) 485-5693", lat: 29.7161, lng: -95.4128 },
  { name: "Goode Company Hamburgers & Taqueria", category: "restaurant", subcategory: "American", address: "4902 Kirby Dr, Houston, TX 77098", description: "Texas-style burgers, tacos, and Tex-Mex favorites from the Goode Company family.", website: "https://www.goodecompany.com", phone: "(713) 520-9153", lat: 29.7200, lng: -95.4125 },
  { name: "Goode Company Seafood", category: "restaurant", subcategory: "Seafood", address: "2621 Westpark Dr, Houston, TX 77098", description: "Fresh Gulf seafood, mesquite-grilled fish, and campechana in a casual Texas setting.", website: "https://www.goodecompany.com", phone: "(713) 523-7154", lat: 29.7205, lng: -95.4130 },
  { name: "Gratify", category: "restaurant", subcategory: "American", address: "2518 University Blvd, Houston, TX 77005", description: "Modern American restaurant with seasonal menus and a focus on local ingredients.", website: "https://www.gratifyrestaurant.com", phone: "(832) 740-4573", lat: 29.7167, lng: -95.4105 },
  { name: "Hamsa", category: "restaurant", subcategory: "Middle Eastern", address: "5555 Morningside Dr, Houston, TX 77005", description: "Contemporary Middle Eastern cuisine with bold flavors and a stylish setting.", website: "https://www.hamsahouston.com", phone: "(713) 485-5559", lat: 29.7157, lng: -95.4140 },
  { name: "Helen Greek Food & Wine", category: "restaurant", subcategory: "Greek", address: "2429 Rice Blvd, Houston, TX 77005", description: "Refined Greek cuisine with an excellent wine list in an elegant atmosphere.", website: "https://www.helengreekfoodandwine.com", phone: "(713) 284-4472", lat: 29.7153, lng: -95.4115 },
  { name: "Highly Recommended", category: "restaurant", subcategory: "American", address: "2501 University Blvd, Houston, TX 77005", description: "Trendy spot serving chef-driven comfort food with a creative flair.", website: "https://www.highlyrecommendedhtx.com", phone: "(832) 668-5573", lat: 29.7166, lng: -95.4118 },
  { name: "Hillstone Restaurant", category: "restaurant", subcategory: "American", address: "4848 Kirby Dr, Houston, TX 77098", description: "Upscale American dining with steaks, seafood, and signature cocktails.", website: "https://www.hillstone.com", phone: "(713) 942-9222", lat: 29.7210, lng: -95.4122 },
  { name: "Hobbit Cafe", category: "restaurant", subcategory: "Vegetarian", address: "2243 Richmond Ave, Houston, TX 77098", description: "Whimsical Tolkien-themed cafe with creative vegetarian and omnivore options.", website: "https://www.hobbitcafe.com", phone: "(713) 526-5460", lat: 29.7185, lng: -95.4155 },
  { name: "Hopdoddy Burger Bar", category: "restaurant", subcategory: "Burgers", address: "2520 University Blvd, Houston, TX 77005", description: "Craft burgers with house-ground patties, hand-cut fries, and spiked shakes.", website: "https://www.hopdoddy.com", phone: "(713) 352-3825", lat: 29.7169, lng: -95.4103 },
  { name: "Hu's Cooking", category: "restaurant", subcategory: "Chinese", address: "2444 Times Blvd, Houston, TX 77005", description: "Authentic Chinese cuisine with Sichuan specialties in an upscale setting.", website: "https://www.huscooking.com", phone: "(713) 965-0808", lat: 29.7149, lng: -95.4110 },
  { name: "Hungry's", category: "restaurant", subcategory: "American", address: "2356 Rice Blvd, Houston, TX 77005", description: "Eclectic neighborhood bistro with diverse menu spanning American, Italian, and Asian.", website: "https://www.hungryshoustontx.com", phone: "(713) 523-8652", lat: 29.7151, lng: -95.4120 },
  { name: "Island Grill", category: "restaurant", subcategory: "Caribbean", address: "2501 Rice Blvd, Houston, TX 77005", description: "Caribbean-inspired dishes with fresh seafood, jerk chicken, and tropical vibes.", website: "https://www.islandgrillhouston.com", phone: "(713) 522-7200", lat: 29.7155, lng: -95.4105 },
  { name: "Istanbul Grill & Deli", category: "restaurant", subcategory: "Turkish", address: "5613 Morningside Dr, Houston, TX 77005", description: "Authentic Turkish cuisine with kebabs, mezes, and imported specialties.", website: "https://www.istanbulgrillhouston.com", phone: "(713) 526-2800", lat: 29.7159, lng: -95.4138 },
  { name: "Jason's Deli", category: "restaurant", subcategory: "Deli", address: "2611 University Blvd, Houston, TX 77005", description: "Fresh deli sandwiches, soups, salads, and a famous free ice cream machine.", website: "https://www.jasonsdeli.com", phone: "(713) 526-3354", lat: 29.7172, lng: -95.4090 },
  { name: "Kim Son Cafe", category: "restaurant", subcategory: "Vietnamese", address: "2508 Rice Blvd, Houston, TX 77005", description: "Vietnamese and Chinese cuisine with pho, banh mi, and dim sum favorites.", website: "https://www.kimson.com", phone: "(713) 527-8388", lat: 29.7157, lng: -95.4100 },
  { name: "KIN by Chef Evelyn", category: "restaurant", subcategory: "Asian Fusion", address: "2412 University Blvd, Houston, TX 77005", description: "Modern Asian fusion cuisine with seasonal tasting menus and craft cocktails.", website: "https://www.kinhouston.com", phone: "(346) 230-4015", lat: 29.7164, lng: -95.4120 },
  { name: "Kolache Factory", category: "restaurant", subcategory: "Bakery", address: "2604 University Blvd, Houston, TX 77005", description: "Fresh-baked Czech kolaches with sweet and savory fillings, plus croissants.", website: "https://www.kolachefactory.com", phone: "(713) 528-1414", lat: 29.7171, lng: -95.4092 },
  { name: "La Fresca Pizza", category: "restaurant", subcategory: "Pizza", address: "2438 University Blvd, Houston, TX 77005", description: "Thin-crust artisan pizzas with fresh toppings and Italian classics.", website: "", phone: "(713) 522-1510", lat: 29.7162, lng: -95.4117 },
  { name: "Le Peep", category: "restaurant", subcategory: "Breakfast", address: "2520 Amherst St, Houston, TX 77005", description: "Classic breakfast and brunch spot with omelets, pancakes, and eggs Benedict.", website: "https://www.lepeep.com", phone: "(713) 522-7337", lat: 29.7145, lng: -95.4108 },
  { name: "Little Matt's", category: "restaurant", subcategory: "American", address: "2521 University Blvd, Houston, TX 77005", description: "Cozy neighborhood restaurant with creative comfort food and a great bar.", website: "https://www.littlematts.com", phone: "(713) 522-1010", lat: 29.7166, lng: -95.4113 },
  { name: "Local Foods", category: "restaurant", subcategory: "Farm-to-Table", address: "2424 Dunstan Rd, Houston, TX 77005", description: "Farm-to-table restaurant sourcing from local Texas farms for sandwiches and salads.", website: "https://www.localfoodshouston.com", phone: "(713) 521-7800", lat: 29.7147, lng: -95.4125 },
  { name: "Mendocino Farms", category: "restaurant", subcategory: "Sandwiches", address: "2510 University Blvd, Houston, TX 77005", description: "Inventive sandwiches and salads made with chef-curated seasonal ingredients.", website: "https://www.mendocinofarms.com", phone: "(346) 318-2349", lat: 29.7168, lng: -95.4107 },
  { name: "Miller's Cafe", category: "restaurant", subcategory: "American", address: "2475 Times Blvd, Houston, TX 77005", description: "Longstanding neighborhood diner serving home-style breakfasts and lunches.", website: "https://www.millerscafehouston.com", phone: "(713) 528-2891", lat: 29.7148, lng: -95.4105 },
  { name: "Nice Sprout Cafe", category: "restaurant", subcategory: "Healthy", address: "2430 Rice Blvd, Houston, TX 77005", description: "Health-focused cafe with smoothie bowls, salads, and plant-based options.", website: "", phone: "", lat: 29.7152, lng: -95.4112 },
  { name: "Oh My Gogi", category: "restaurant", subcategory: "Korean", address: "Rice Village, Houston, TX 77005", description: "Korean-Mexican fusion food truck known for Korean BBQ tacos and kimchi fries.", website: "https://www.ohmygogi.com", phone: "(713) 521-4622", lat: 29.7160, lng: -95.4095 },
  { name: "Pacha Nikkei", category: "restaurant", subcategory: "Peruvian-Japanese", address: "2440 Times Blvd, Houston, TX 77005", description: "Peruvian-Japanese fusion with ceviches, tiraditos, and creative small plates.", website: "https://www.pachanikkei.com", phone: "(713) 521-7070", lat: 29.7150, lng: -95.4115 },
  { name: "Pasha Turkish Restaurant", category: "restaurant", subcategory: "Turkish", address: "2529 University Blvd, Houston, TX 77005", description: "Authentic Turkish dishes with fresh-baked pide, kebabs, and baklava.", website: "https://www.pashaturkishrestaurant.com", phone: "(713) 592-0020", lat: 29.7165, lng: -95.4108 },
  { name: "Poblano's", category: "restaurant", subcategory: "Mexican", address: "2433 University Blvd, Houston, TX 77005", description: "Traditional Mexican fare with sizzling fajitas and house-made tortillas.", website: "", phone: "(713) 522-3648", lat: 29.7161, lng: -95.4132 },
  { name: "Pokeworks", category: "restaurant", subcategory: "Hawaiian", address: "2522 University Blvd, Houston, TX 77005", description: "Build-your-own poke bowls with fresh fish, creative toppings, and signature sauces.", website: "https://www.pokeworks.com", phone: "(713) 485-5888", lat: 29.7169, lng: -95.4102 },
  { name: "Politan Row Houston", category: "restaurant", subcategory: "Food Hall", address: "2445 Times Blvd, Houston, TX 77005", description: "Gourmet food hall featuring multiple chef-driven concepts under one roof.", website: "https://www.politanrow.com", phone: "(832) 519-3301", lat: 29.7149, lng: -95.4108 },
  { name: "Prego", category: "restaurant", subcategory: "Italian", address: "2520 Amherst St, Houston, TX 77005", description: "Classic Italian dishes with homemade pasta and a warm, romantic setting.", website: "https://www.pregohouston.com", phone: "(713) 529-2420", lat: 29.7146, lng: -95.4110 },
  { name: "Prima Pasta", category: "restaurant", subcategory: "Italian", address: "2435 Times Blvd, Houston, TX 77005", description: "Fresh Italian pasta dishes and traditional recipes in a cozy trattoria.", website: "", phone: "(713) 529-0900", lat: 29.7148, lng: -95.4112 },
  { name: "Roma", category: "restaurant", subcategory: "Italian", address: "2347 University Blvd, Houston, TX 77005", description: "Upscale Italian dining with hand-cut pastas, seafood, and fine wines.", website: "https://www.romahouston.com", phone: "(713) 521-3333", lat: 29.7159, lng: -95.4140 },
  { name: "Safina", category: "restaurant", subcategory: "Mediterranean", address: "2440 University Blvd, Houston, TX 77005", description: "Mediterranean-inspired dishes with a focus on fresh, seasonal flavors.", website: "https://www.safinahouston.com", phone: "(713) 522-0999", lat: 29.7163, lng: -95.4116 },
  { name: "Salata", category: "restaurant", subcategory: "Salads", address: "2515 University Blvd, Houston, TX 77005", description: "Build-your-own salads and wraps with fresh ingredients and house-made dressings.", website: "https://www.salata.com", phone: "(713) 521-3399", lat: 29.7167, lng: -95.4112 },
  { name: "Salento Bistrot", category: "restaurant", subcategory: "Italian", address: "2444 University Blvd, Houston, TX 77005", description: "Southern Italian bistro with regional specialties and a curated wine list.", website: "https://www.salentobistrot.com", phone: "(713) 714-4474", lat: 29.7163, lng: -95.4113 },
  { name: "Seco's Latin Cuisine", category: "restaurant", subcategory: "Latin", address: "2501 Times Blvd, Houston, TX 77005", description: "Latin American flavors with Cuban sandwiches, empanadas, and tropical drinks.", website: "https://www.secoslatincuisine.com", phone: "(713) 528-4547", lat: 29.7147, lng: -95.4100 },
  { name: "Shiva Indian Restaurant", category: "restaurant", subcategory: "Indian", address: "2514 Times Blvd, Houston, TX 77005", description: "Authentic Indian cuisine with tandoori, curries, and a popular lunch buffet.", website: "https://www.shivaindianrestaurant.com", phone: "(713) 523-4753", lat: 29.7148, lng: -95.4098 },
  { name: "Southwell's Hamburger Grill", category: "restaurant", subcategory: "Burgers", address: "2252 Holcombe Blvd, Houston, TX 77030", description: "Old-school burger joint with juicy patties, hand-cut fries, and milkshakes.", website: "https://www.southwellsburgers.com", phone: "(713) 520-0033", lat: 29.7135, lng: -95.4100 },
  { name: "Sweet Paris", category: "restaurant", subcategory: "Crepes", address: "2420 University Blvd, Houston, TX 77005", description: "Parisian-style creperie with sweet and savory crepes, macarons, and coffee.", website: "https://www.sweetparis.com", phone: "(713) 520-8099", lat: 29.7164, lng: -95.4122 },
  { name: "sweetgreen", category: "restaurant", subcategory: "Salads", address: "2530 University Blvd, Houston, TX 77005", description: "Seasonal salads and grain bowls made with locally sourced, organic ingredients.", website: "https://www.sweetgreen.com", phone: "(713) 955-5095", lat: 29.7170, lng: -95.4098 },
  { name: "Tamashi", category: "restaurant", subcategory: "Japanese", address: "2438 Times Blvd, Houston, TX 77005", description: "Ramen and Japanese soul food with rich broths and handmade noodles.", website: "https://www.tamashiramen.com", phone: "(713) 524-6988", lat: 29.7150, lng: -95.4113 },
  { name: "Taste of Spices", category: "restaurant", subcategory: "Indian", address: "2502 University Blvd, Houston, TX 77005", description: "Flavorful Indian dishes with a blend of traditional and modern preparations.", website: "", phone: "(713) 521-1010", lat: 29.7168, lng: -95.4110 },
  { name: "Thai Village Restaurant", category: "restaurant", subcategory: "Thai", address: "5310 Morningside Dr, Houston, TX 77005", description: "Family-owned Thai restaurant with authentic curries, pad thai, and stir-fries.", website: "", phone: "(713) 521-2092", lat: 29.7153, lng: -95.4145 },
  { name: "The Bistro", category: "restaurant", subcategory: "American", address: "2438 University Blvd, Houston, TX 77005", description: "Eat. Drink. Connect. Modern bistro with eclectic American fare and craft drinks.", website: "", phone: "(713) 524-8770", lat: 29.7162, lng: -95.4118 },
  { name: "The Halal Guys", category: "restaurant", subcategory: "Middle Eastern", address: "2524 University Blvd, Houston, TX 77005", description: "NYC-famous halal street food with platters of chicken, gyro, and white sauce.", website: "https://www.thehalalguys.com", phone: "(713) 588-3588", lat: 29.7169, lng: -95.4101 },
  { name: "The Lexington Grille", category: "restaurant", subcategory: "American", address: "2525 University Blvd, Houston, TX 77005", description: "Classic American grille with steaks, seafood, and a refined cocktail menu.", website: "https://www.thelexingtongrille.com", phone: "(713) 528-0014", lat: 29.7166, lng: -95.4110 },
  { name: "The Raven Grill", category: "restaurant", subcategory: "American", address: "2416 Times Blvd, Houston, TX 77005", description: "Neighborhood grill with comfort food favorites, burgers, and a friendly bar.", website: "", phone: "(713) 521-2027", lat: 29.7149, lng: -95.4118 },
  { name: "Tiger Noodle House", category: "restaurant", subcategory: "Chinese", address: "2512 Rice Blvd, Houston, TX 77005", description: "Hand-pulled noodles and authentic Chinese dishes in a casual atmosphere.", website: "", phone: "(713) 527-9588", lat: 29.7156, lng: -95.4097 },
  { name: "Tiny's No. 5", category: "restaurant", subcategory: "American", address: "3636 Rice Blvd, Houston, TX 77005", description: "Charming neighborhood spot with a seasonal American menu and lovely patio.", website: "https://www.tinysno5.com", phone: "(713) 529-0100", lat: 29.7150, lng: -95.4080 },
  { name: "True Food Kitchen", category: "restaurant", subcategory: "Healthy", address: "2600 University Blvd, Houston, TX 77005", description: "Health-driven seasonal menu inspired by Dr. Andrew Weil's anti-inflammatory diet.", website: "https://www.truefoodkitchen.com", phone: "(832) 831-5503", lat: 29.7171, lng: -95.4093 },
  { name: "Two Guys Pizzeria", category: "restaurant", subcategory: "Pizza", address: "2435 University Blvd, Houston, TX 77005", description: "New York-style pizza with hand-tossed dough and classic Italian-American dishes.", website: "", phone: "(713) 523-0099", lat: 29.7161, lng: -95.4130 },
  { name: "Velvet Taco", category: "restaurant", subcategory: "Tacos", address: "2610 University Blvd, Houston, TX 77005", description: "Inventive tacos with globally inspired fillings and a laid-back vibe.", website: "https://www.velvettaco.com", phone: "(713) 301-5753", lat: 29.7172, lng: -95.4088 },
  { name: "Whataburger", category: "restaurant", subcategory: "Fast Food", address: "2505 University Blvd, Houston, TX 77005", description: "Iconic Texas burger chain with made-to-order burgers and breakfast taquitos.", website: "https://www.whataburger.com", phone: "(713) 523-2695", lat: 29.7166, lng: -95.4115 },
  { name: "Zoe's Kitchen", category: "restaurant", subcategory: "Mediterranean", address: "2528 University Blvd, Houston, TX 77005", description: "Mediterranean-inspired dishes with fresh ingredients, hummus, and grilled proteins.", website: "https://www.zoeskitchen.com", phone: "(713) 527-0604", lat: 29.7170, lng: -95.4100 },

  // ============================================
  // BARS & LOUNGES
  // ============================================
  { name: "Anvil Bar & Refuge", category: "bar", subcategory: "Cocktail Bar", address: "1424 Westheimer Rd, Houston, TX 77006", description: "Award-winning craft cocktail bar with rotating seasonal menus and expert mixologists.", website: "https://www.anvilhouston.com", phone: "(713) 523-1622", lat: 29.7440, lng: -95.3870 },
  { name: "Bacco", category: "bar", subcategory: "Wine Bar", address: "2437 University Blvd, Houston, TX 77005", description: "Italian wine bar with curated wine list, small plates, and romantic ambiance.", website: "https://www.baccowineandspirits.com", phone: "(713) 524-2426", lat: 29.7161, lng: -95.4127 },
  { name: "Bar 2200", category: "bar", subcategory: "Cocktail Bar", address: "2200 Southwest Fwy, Houston, TX 77098", description: "Stylish cocktail lounge with craft drinks and an upscale atmosphere.", website: "", phone: "(713) 521-2200", lat: 29.7215, lng: -95.4160 },
  { name: "Bar 9", category: "bar", subcategory: "Dive Bar", address: "2409 Grant St, Houston, TX 77006", description: "No-frills neighborhood dive with cheap drinks and an iconic jukebox.", website: "", phone: "(713) 526-2090", lat: 29.7200, lng: -95.4080 },
  { name: "Bar Esperanto", category: "bar", subcategory: "Cocktail Bar", address: "2505 Kirby Dr, Houston, TX 77019", description: "Intimate cocktail bar with globally inspired drinks and a cozy vibe.", website: "", phone: "", lat: 29.7300, lng: -95.4120 },
  { name: "Boondocks", category: "bar", subcategory: "Dive Bar", address: "5706 Richmond Ave, Houston, TX 77057", description: "Classic Houston dive bar with pool tables, darts, and cold beer.", website: "https://www.boondockshouston.com", phone: "(713) 526-2300", lat: 29.7230, lng: -95.4600 },
  { name: "Capone's Oven & Bar", category: "bar", subcategory: "Sports Bar", address: "2426 University Blvd, Houston, TX 77005", description: "Pizza, pasta, and cocktails with a fun Prohibition-era theme.", website: "https://www.caponesoven.com", phone: "(713) 621-9060", lat: 29.7164, lng: -95.4121 },
  { name: "Christians Tailgate", category: "bar", subcategory: "Sports Bar", address: "2000 Bagby St, Houston, TX 77002", description: "Laid-back sports bar with great burgers, outdoor patio, and big screens.", website: "https://www.christianstailgate.com", phone: "(713) 527-0261", lat: 29.7530, lng: -95.3730 },
  { name: "Dino's Den", category: "bar", subcategory: "Dive Bar", address: "2417 Times Blvd, Houston, TX 77005", description: "Beloved Rice Village dive with strong drinks and late-night vibes.", website: "", phone: "(713) 522-0091", lat: 29.7149, lng: -95.4116 },
  { name: "Downing Street Social Club", category: "bar", subcategory: "Pub", address: "2549 Kirby Dr, Houston, TX 77019", description: "British-inspired social club with cocktails, beer, and a refined atmosphere.", website: "", phone: "(832) 742-5082", lat: 29.7290, lng: -95.4118 },
  { name: "Elie Live Music Wine Bar", category: "bar", subcategory: "Wine Bar", address: "2412 Times Blvd, Houston, TX 77005", description: "Wine bar with live jazz, blues, and acoustic performances in an intimate setting.", website: "", phone: "", lat: 29.7149, lng: -95.4120 },
  { name: "Grand Prize Bar", category: "bar", subcategory: "Dive Bar", address: "1318 Westheimer Rd, Houston, TX 77006", description: "Retro-themed bar with pinball, cheap drinks, and a great outdoor patio.", website: "https://www.grandprizebar.com", phone: "(713) 526-4565", lat: 29.7445, lng: -95.3855 },
  { name: "Kirbside Bar", category: "bar", subcategory: "Dive Bar", address: "2531 University Blvd, Houston, TX 77005", description: "Laid-back patio bar on Kirby with cold beers and a neighborhood feel.", website: "", phone: "", lat: 29.7166, lng: -95.4107 },
  { name: "Kirby Ice House", category: "bar", subcategory: "Beer Garden", address: "3333 Eastside St, Houston, TX 77098", description: "Massive outdoor beer garden with lawn games, food trucks, and a huge beer selection.", website: "https://www.kirbyicehouse.com", phone: "(713) 521-1000", lat: 29.7250, lng: -95.4115 },
  { name: "La Bar", category: "bar", subcategory: "Cocktail Bar", address: "2425 Times Blvd, Houston, TX 77005", description: "Chic cocktail bar with craft drinks and a vibrant Latin-inspired atmosphere.", website: "", phone: "", lat: 29.7148, lng: -95.4114 },
  { name: "Little Woodrow's Bellaire", category: "bar", subcategory: "Sports Bar", address: "5611 Morningside Dr, Houston, TX 77005", description: "Sports bar with big screens, cold beer, and a great outdoor patio.", website: "https://www.littlewoodrows.com", phone: "(713) 661-4200", lat: 29.7158, lng: -95.4137 },
  { name: "Little Woodrow's Rice Village", category: "bar", subcategory: "Sports Bar", address: "2306 Brazos St, Houston, TX 77006", description: "Popular spot for watching games with friends over buckets of beer.", website: "https://www.littlewoodrows.com", phone: "(713) 521-2337", lat: 29.7180, lng: -95.4090 },
  { name: "Lizzard's Pub", category: "bar", subcategory: "Pub", address: "2438 University Blvd, Houston, TX 77005", description: "Classic neighborhood pub with darts, pool, and a loyal local crowd.", website: "", phone: "(713) 528-9453", lat: 29.7163, lng: -95.4119 },
  { name: "Marquis II", category: "bar", subcategory: "Dive Bar", address: "2631 University Blvd, Houston, TX 77005", description: "Longstanding Rice Village dive with character, cheap pints, and a jukebox.", website: "https://www.marquisiibar.com", phone: "(713) 526-2625", lat: 29.7173, lng: -95.4086 },
  { name: "McElroy's Pub", category: "bar", subcategory: "Irish Pub", address: "2421 University Blvd, Houston, TX 77005", description: "Irish-style pub with Guinness on draft, pub grub, and a cozy atmosphere.", website: "", phone: "(713) 523-2028", lat: 29.7160, lng: -95.4133 },
  { name: "McGonigel's Mucky Duck", category: "bar", subcategory: "Live Music", address: "2425 Norfolk St, Houston, TX 77098", description: "Iconic Houston live music venue featuring folk, acoustic, and Americana acts.", website: "https://www.mcgonigels.com", phone: "(713) 528-5999", lat: 29.7240, lng: -95.4200 },
  { name: "Olive + Twist Bar", category: "bar", subcategory: "Cocktail Bar", address: "2424 Dunstan Rd, Houston, TX 77005", description: "Upscale cocktail lounge with handcrafted drinks and modern small plates.", website: "", phone: "", lat: 29.7146, lng: -95.4123 },
  { name: "On The Kirb", category: "bar", subcategory: "Bar & Grill", address: "2535 University Blvd, Houston, TX 77005", description: "Casual bar and grill with good food, live music, and a fun atmosphere.", website: "", phone: "", lat: 29.7166, lng: -95.4105 },
  { name: "Penny Whistle Pub", category: "bar", subcategory: "Pub", address: "2434 University Blvd, Houston, TX 77005", description: "Cozy pub with a big beer selection, trivia nights, and friendly service.", website: "", phone: "(713) 522-2010", lat: 29.7163, lng: -95.4118 },
  { name: "Poison Girl", category: "bar", subcategory: "Dive Bar", address: "1641 Westheimer Rd, Houston, TX 77006", description: "Punk-rock dive with cheap whiskey, great jukebox, and a killer patio.", website: "https://www.poisongirlbar.com", phone: "(713) 527-9929", lat: 29.7430, lng: -95.3920 },
  { name: "Red Lion British Pub", category: "bar", subcategory: "British Pub", address: "2316 S Shepherd Dr, Houston, TX 77019", description: "Authentic British pub with fish & chips, meat pies, and proper pints.", website: "https://www.redlionhouston.com", phone: "(713) 782-3030", lat: 29.7270, lng: -95.4100 },
  { name: "Revelry on Richmond", category: "bar", subcategory: "Bar & Grill", address: "1613 Richmond Ave, Houston, TX 77006", description: "Funky neighborhood bar with live music, food trucks, and a large patio.", website: "https://www.revelryonrichmond.com", phone: "(713) 528-3900", lat: 29.7350, lng: -95.3900 },
  { name: "Rye 51", category: "bar", subcategory: "Whiskey Bar", address: "2511 University Blvd, Houston, TX 77005", description: "Whiskey-focused bar with an impressive bourbon selection and craft cocktails.", website: "", phone: "", lat: 29.7167, lng: -95.4114 },
  { name: "Simone on Sunset", category: "bar", subcategory: "Lounge", address: "2436 Bissonnet St, Houston, TX 77005", description: "Sophisticated lounge with cocktails, small plates, and a stylish setting.", website: "https://www.simoneonsunset.com", phone: "(713) 505-7350", lat: 29.7140, lng: -95.4115 },
  { name: "Sixty Vines", category: "bar", subcategory: "Wine Bar", address: "2540 University Blvd, Houston, TX 77005", description: "Wine-on-tap restaurant with 60 wines by the glass and seasonal cuisine.", website: "https://www.sixtyvines.com", phone: "(832) 740-4660", lat: 29.7170, lng: -95.4099 },
  { name: "T.K. Bitterman's", category: "bar", subcategory: "Cocktail Bar", address: "2419 Times Blvd, Houston, TX 77005", description: "Speakeasy-style cocktail lounge with vintage charm and expert mixology.", website: "https://www.tkbittermans.com", phone: "(713) 521-3350", lat: 29.7148, lng: -95.4115 },
  { name: "The Cedar Bar", category: "bar", subcategory: "Bar", address: "2420 University Blvd, Houston, TX 77005", description: "Modern bar with craft cocktails, local beers, and a relaxed atmosphere.", website: "", phone: "", lat: 29.7164, lng: -95.4123 },
  { name: "The Cellar Bar", category: "bar", subcategory: "Wine Bar", address: "2506 University Blvd, Houston, TX 77005", description: "Underground wine cellar bar with an extensive collection and tasting events.", website: "", phone: "(713) 521-9100", lat: 29.7168, lng: -95.4112 },
  { name: "The Davenport", category: "bar", subcategory: "Lounge", address: "2505 Washington Ave, Houston, TX 77007", description: "Upscale lounge with craft cocktails, live DJs, and a glamorous vibe.", website: "https://www.thedavenporthouston.com", phone: "(713) 526-8900", lat: 29.7650, lng: -95.3800 },
  { name: "The Key", category: "bar", subcategory: "Cocktail Bar", address: "2418 Times Blvd, Houston, TX 77005", description: "Intimate cocktail spot with creative drinks and a neighborhood feel.", website: "", phone: "", lat: 29.7149, lng: -95.4117 },
  { name: "The Owl", category: "bar", subcategory: "Bar", address: "2439 University Blvd, Houston, TX 77005", description: "Trendy bar with inventive cocktails and a late-night menu.", website: "", phone: "", lat: 29.7161, lng: -95.4126 },
  { name: "The Patio at The Pit Room", category: "bar", subcategory: "BBQ Bar", address: "1201 Richmond Ave, Houston, TX 77006", description: "Texas BBQ meets craft cocktails on a spacious outdoor patio.", website: "https://www.thepitroombbq.com", phone: "(281) 888-1929", lat: 29.7360, lng: -95.3840 },
  { name: "The Phoenix on Westheimer", category: "bar", subcategory: "Bar", address: "1915 Westheimer Rd, Houston, TX 77098", description: "Chill neighborhood bar with strong drinks, friendly staff, and a dog-friendly patio.", website: "https://www.thephoenixonwestheimer.com", phone: "(713) 522-5862", lat: 29.7418, lng: -95.3975 },
  { name: "The Tipsy Dessert Bar", category: "bar", subcategory: "Dessert Bar", address: "2436 University Blvd, Houston, TX 77005", description: "Unique dessert-meets-cocktails concept with boozy treats and creative drinks.", website: "", phone: "", lat: 29.7163, lng: -95.4120 },
  { name: "Twin Peaks Kirby", category: "bar", subcategory: "Sports Bar", address: "5250 Buffalo Speedway, Houston, TX 77005", description: "Lodge-themed sports bar with cold beer, big screens, and comfort food.", website: "https://www.twinpeaksrestaurant.com", phone: "(713) 526-2900", lat: 29.7178, lng: -95.4175 },
  { name: "Under the Volcano", category: "bar", subcategory: "Dive Bar", address: "2349 Bissonnet St, Houston, TX 77005", description: "Legendary Houston dive with strong drinks, eclectic decor, and a loyal crowd.", website: "", phone: "(713) 526-5282", lat: 29.7142, lng: -95.4125 },
  { name: "Upstairs", category: "bar", subcategory: "Lounge", address: "2420 Rice Blvd, Houston, TX 77005", description: "Second-floor lounge with craft cocktails, DJs, and a vibrant nightlife scene.", website: "", phone: "", lat: 29.7152, lng: -95.4113 },
  { name: "Valhalla", category: "bar", subcategory: "College Bar", address: "6100 Main St, Houston, TX 77005", description: "Rice University's beloved on-campus pub with cheap beer and a graduate-student vibe.", website: "https://www.valhallabar.com", phone: "(713) 348-3258", lat: 29.7165, lng: -95.4030 },
  { name: "Velvet Melvin Pub", category: "bar", subcategory: "Pub", address: "2441 University Blvd, Houston, TX 77005", description: "Low-key pub with affordable drinks, pool tables, and a laid-back atmosphere.", website: "", phone: "(713) 522-9205", lat: 29.7162, lng: -95.4124 },
  { name: "West Alabama Ice House", category: "bar", subcategory: "Beer Garden", address: "1919 W Alabama St, Houston, TX 77098", description: "Houston institution — open-air beer joint with picnic tables and a relaxed vibe.", website: "https://www.westalabamicehouse.com", phone: "(713) 528-6874", lat: 29.7390, lng: -95.3980 },
  { name: "Willy's Pub", category: "bar", subcategory: "College Bar", address: "6100 Main St, Houston, TX 77005", description: "Rice University student-run pub with cheap drinks and campus community.", website: "", phone: "(713) 348-3258", lat: 29.7163, lng: -95.4032 },

  // ============================================
  // COFFEE SHOPS & CAFES
  // ============================================
  { name: "Agnes", category: "coffee", subcategory: "Cafe", address: "2441 University Blvd, Houston, TX 77005", description: "Artisan cafe with pour-over coffees, fresh pastries, and a minimalist aesthetic.", website: "https://www.agnescafehouston.com", phone: "(832) 785-4537", lat: 29.7161, lng: -95.4125 },
  { name: "Agora", category: "coffee", subcategory: "Coffee House", address: "1712 Westheimer Rd, Houston, TX 77098", description: "European-style coffeehouse with an artistic atmosphere, open late.", website: "https://www.agorahouston.com", phone: "(713) 526-7212", lat: 29.7425, lng: -95.3940 },
  { name: "Al Vetro", category: "coffee", subcategory: "Cafe", address: "2500 University Blvd, Houston, TX 77005", description: "Italian-inspired cafe with espresso, gelato, and light bites.", website: "https://www.alvetrogelato.com", phone: "(713) 526-1897", lat: 29.7168, lng: -95.4112 },
  { name: "Anonymous Cafe", category: "coffee", subcategory: "Cafe", address: "2438 University Blvd, Houston, TX 77005", description: "Cozy hidden gem with specialty coffee, teas, and homemade baked goods.", website: "https://www.anonymouscafe.com", phone: "(832) 538-1339", lat: 29.7163, lng: -95.4117 },
  { name: "Bebidas", category: "coffee", subcategory: "Cafe", address: "2604 University Blvd, Houston, TX 77005", description: "Latin-inspired coffee and juice bar with specialty drinks and smoothies.", website: "https://www.bebidascoffee.com", phone: "(713) 524-5765", lat: 29.7171, lng: -95.4091 },
  { name: "Black Hole Coffee House", category: "coffee", subcategory: "Coffee House", address: "4504 Graustark St, Houston, TX 77006", description: "Quirky neighborhood coffee shop with house-roasted beans and free WiFi.", website: "https://www.blackholecoffeehouse.com", phone: "(713) 528-0653", lat: 29.7320, lng: -95.4020 },
  { name: "Cavo Coffee", category: "coffee", subcategory: "Coffee Shop", address: "5216 Morningside Dr, Houston, TX 77005", description: "Third-wave coffee shop with single-origin roasts and a sleek setting.", website: "https://www.cavocoffee.com", phone: "(713) 522-2286", lat: 29.7152, lng: -95.4146 },
  { name: "Christo Mio", category: "coffee", subcategory: "Cafe", address: "2442 University Blvd, Houston, TX 77005", description: "Cozy cafe with Italian espresso, crepes, and homemade pastries.", website: "", phone: "(832) 649-4785", lat: 29.7163, lng: -95.4115 },
  { name: "Common Bond Bistro & Bakery", category: "coffee", subcategory: "Bakery", address: "1706 Westheimer Rd, Houston, TX 77098", description: "Artisan bakery with French-inspired pastries, breads, and specialty coffee.", website: "https://www.commonbondcafe.com", phone: "(713) 529-3535", lat: 29.7425, lng: -95.3942 },
  { name: "Cool Beans Cafe and Bakery", category: "coffee", subcategory: "Cafe", address: "2438 University Blvd, Houston, TX 77005", description: "Friendly cafe with fresh-baked treats, gourmet coffee, and a welcoming vibe.", website: "", phone: "(713) 523-7071", lat: 29.7162, lng: -95.4116 },
  { name: "Corner Bakery Cafe", category: "coffee", subcategory: "Bakery", address: "2502 University Blvd, Houston, TX 77005", description: "Bakery cafe with scratch-made pastries, sandwiches, and breakfast items.", website: "https://www.cornerbakerycafe.com", phone: "(713) 523-3663", lat: 29.7168, lng: -95.4111 },
  { name: "Dunkin'", category: "coffee", subcategory: "Coffee Chain", address: "2525 University Blvd, Houston, TX 77005", description: "America's favorite coffee and donut chain with drive-through convenience.", website: "https://www.dunkindonuts.com", phone: "(713) 665-2515", lat: 29.7166, lng: -95.4109 },
  { name: "Einstein Bros. Bagels", category: "coffee", subcategory: "Bagel Shop", address: "5507 Kelvin Dr, Houston, TX 77005", description: "Fresh-baked bagels, schmears, and signature coffee and espresso drinks.", website: "https://www.einsteinbros.com", phone: "(713) 526-2095", lat: 29.7157, lng: -95.4050 },
  { name: "Empire Cafe", category: "coffee", subcategory: "Cafe", address: "1732 Westheimer Rd, Houston, TX 77098", description: "Popular Montrose cafe with great coffee, pastries, and people-watching.", website: "https://www.empirecafe.com", phone: "(713) 528-5282", lat: 29.7423, lng: -95.3935 },
  { name: "Fannin Street Cafe", category: "coffee", subcategory: "Cafe", address: "6500 Fannin St, Houston, TX 77030", description: "Casual cafe near the Medical Center with sandwiches and coffee.", website: "", phone: "(713) 522-0880", lat: 29.7120, lng: -95.3970 },
  { name: "Fellini Caffe", category: "coffee", subcategory: "Italian Cafe", address: "700 W Dallas St, Houston, TX 77019", description: "Italian-style cafe with espresso, gelato, and imported treats.", website: "https://www.fellinicaffe.com", phone: "(713) 524-2994", lat: 29.7580, lng: -95.3770 },
  { name: "Ginger Kale", category: "coffee", subcategory: "Juice Bar", address: "2440 University Blvd, Houston, TX 77005", description: "Health-conscious cafe with cold-pressed juices, smoothies, and acai bowls.", website: "https://www.gingerkale.com", phone: "(346) 231-7057", lat: 29.7163, lng: -95.4114 },
  { name: "Greenway Coffee", category: "coffee", subcategory: "Coffee Shop", address: "3336 Westpark Dr, Houston, TX 77005", description: "Neighborhood coffee roaster with carefully sourced beans and cozy seating.", website: "https://www.greenwaycoffee.com", phone: "(713) 521-1818", lat: 29.7218, lng: -95.4350 },
  { name: "Grinder's Coffee Bar", category: "coffee", subcategory: "Coffee Shop", address: "2418 University Blvd, Houston, TX 77005", description: "No-nonsense coffee bar with strong espresso, pastries, and a quick serve.", website: "", phone: "(713) 668-2829", lat: 29.7164, lng: -95.4124 },
  { name: "Honey Art Cafe", category: "coffee", subcategory: "Cafe", address: "2506 University Blvd, Houston, TX 77005", description: "Artistic cafe combining gallery space with specialty coffee and sweets.", website: "https://www.honeyartcafe.com", phone: "(713) 524-2990", lat: 29.7168, lng: -95.4111 },
  { name: "Kaffeine Coffee", category: "coffee", subcategory: "Coffee Shop", address: "2510 University Blvd, Houston, TX 77005", description: "Local coffee shop with house-roasted beans, loose-leaf teas, and pastries.", website: "https://www.kaffeinecoffee.com", phone: "(713) 528-5483", lat: 29.7168, lng: -95.4108 },
  { name: "Luce Coffee Roasters", category: "coffee", subcategory: "Roastery", address: "2515 University Blvd, Houston, TX 77005", description: "Micro-roastery with expertly roasted single-origin coffee and pour-overs.", website: "https://www.lucecoffeeroasters.com", phone: "(832) 804-6055", lat: 29.7167, lng: -95.4113 },
  { name: "MFA Cafe", category: "coffee", subcategory: "Museum Cafe", address: "1001 Bissonnet St, Houston, TX 77005", description: "Cafe inside the Museum of Fine Arts with light bites and quality coffee.", website: "https://www.mfah.org", phone: "(713) 639-7300", lat: 29.7255, lng: -95.3908 },
  { name: "Mictlan Coffee Roasters", category: "coffee", subcategory: "Roastery", address: "2434 University Blvd, Houston, TX 77005", description: "Specialty coffee roaster with beans sourced from Latin American farms.", website: "https://www.mictlancoffee.com", phone: "(832) 582-5928", lat: 29.7163, lng: -95.4119 },
  { name: "Panera Bread", category: "coffee", subcategory: "Bakery Cafe", address: "2505 University Blvd, Houston, TX 77005", description: "Bakery cafe with fresh bread, soups, salads, and specialty coffee drinks.", website: "https://www.panerabread.com", phone: "(713) 432-1011", lat: 29.7166, lng: -95.4116 },
  { name: "Periodic Table", category: "coffee", subcategory: "Cafe", address: "2520 University Blvd, Houston, TX 77005", description: "Science-themed cafe with creative drinks, coffee, and a fun atmosphere.", website: "https://www.periodictablehou.com", phone: "(832) 582-4243", lat: 29.7169, lng: -95.4104 },
  { name: "Purple Kow", category: "coffee", subcategory: "Boba Tea", address: "2443 Times Blvd, Houston, TX 77005", description: "Boba tea shop with a huge variety of milk teas, fruit teas, and toppings.", website: "https://www.purplekow.com", phone: "(713) 521-2246", lat: 29.7149, lng: -95.4109 },
  { name: "Rice Coffeehouse", category: "coffee", subcategory: "Coffee House", address: "6100 Main St, Houston, TX 77005", description: "Rice University campus coffeehouse run by students with a cozy vibe.", website: "https://www.ricecoffeehouse.org", phone: "", lat: 29.7164, lng: -95.4035 },
  { name: "Rustika Cafe and Bakery", category: "coffee", subcategory: "Bakery", address: "3237 Southwest Fwy, Houston, TX 77027", description: "Central American-inspired bakery with tres leches, pastries, and coffee.", website: "https://www.rustikacafe.com", phone: "(713) 432-9882", lat: 29.7330, lng: -95.4300 },
  { name: "Siphon Coffee", category: "coffee", subcategory: "Specialty Coffee", address: "701 W Alabama St, Houston, TX 77006", description: "Specialty coffee shop using siphon brewing method for a unique flavor experience.", website: "https://www.siphoncoffee.com", phone: "(832) 742-4621", lat: 29.7380, lng: -95.3850 },
  { name: "Slowpokes", category: "coffee", subcategory: "Cafe", address: "2425 University Blvd, Houston, TX 77005", description: "Relaxed cafe with slow-drip coffee, pastries, and a neighborhood feel.", website: "https://www.slowpokeshouston.com", phone: "(713) 364-8813", lat: 29.7161, lng: -95.4134 },
  { name: "Starbucks", category: "coffee", subcategory: "Coffee Chain", address: "2522 University Blvd, Houston, TX 77005", description: "Global coffee chain with signature espresso drinks, Frappuccinos, and snacks.", website: "https://www.starbucks.com", phone: "(713) 523-0145", lat: 29.7169, lng: -95.4103 },
  { name: "The Chocolate Bar", category: "coffee", subcategory: "Dessert", address: "2521 University Blvd, Houston, TX 77005", description: "Chocolate lover's paradise with decadent desserts, hot cocoa, and coffee.", website: "https://www.theoriginalchocolatebar.com", phone: "(713) 520-8599", lat: 29.7166, lng: -95.4112 },
  { name: "The Teahouse", category: "coffee", subcategory: "Tea House", address: "2424 University Blvd, Houston, TX 77005", description: "Tranquil tea house with loose-leaf teas from around the world.", website: "https://www.theteahousehouston.com", phone: "(713) 524-0566", lat: 29.7164, lng: -95.4121 },

  // ============================================
  // RETAIL / SHOPPING
  // ============================================
  { name: "Abejas Boutique", category: "shopping", subcategory: "Women's Fashion", address: "2424 Rice Blvd, Houston, TX 77005", description: "Curated women's boutique with designer clothing, jewelry, and accessories.", website: "https://www.abejasboutique.com", phone: "(713) 526-5200", lat: 29.7152, lng: -95.4115 },
  { name: "Altar'd State", category: "shopping", subcategory: "Women's Fashion", address: "2516 University Blvd, Houston, TX 77005", description: "Women's fashion boutique with a bohemian-chic aesthetic and home decor.", website: "https://www.altardstate.com", phone: "(713) 364-8498", lat: 29.7168, lng: -95.4109 },
  { name: "Ann Taylor", category: "shopping", subcategory: "Women's Fashion", address: "2502 University Blvd, Houston, TX 77005", description: "Classic women's workwear and sophisticated everyday fashion.", website: "https://www.anntaylor.com", phone: "(713) 527-0707", lat: 29.7168, lng: -95.4112 },
  { name: "Artisan Designs LLC", category: "shopping", subcategory: "Art & Gifts", address: "2438 University Blvd, Houston, TX 77005", description: "Handcrafted artisan goods, custom jewelry, and unique gift items.", website: "", phone: "(713) 533-1286", lat: 29.7162, lng: -95.4117 },
  { name: "Athleta", category: "shopping", subcategory: "Activewear", address: "2532 University Blvd, Houston, TX 77005", description: "Performance and lifestyle wear for active women by Gap Inc.", website: "https://www.athleta.com", phone: "(713) 322-6048", lat: 29.7170, lng: -95.4098 },
  { name: "Banana Republic", category: "shopping", subcategory: "Fashion", address: "2518 University Blvd, Houston, TX 77005", description: "Modern, refined clothing and accessories for men and women.", website: "https://www.bananarepublic.com", phone: "(713) 529-3020", lat: 29.7169, lng: -95.4106 },
  { name: "Beehive Houston", category: "shopping", subcategory: "Gifts & Home", address: "2437 University Blvd, Houston, TX 77005", description: "Eclectic gift shop with home decor, novelties, and Houston-themed souvenirs.", website: "https://www.beehivehouston.com", phone: "(832) 360-7784", lat: 29.7161, lng: -95.4126 },
  { name: "Cariloha Bamboo", category: "shopping", subcategory: "Lifestyle", address: "2508 University Blvd, Houston, TX 77005", description: "Eco-friendly bamboo clothing, bedding, and bath products.", website: "https://www.cariloha.com", phone: "(713) 955-4448", lat: 29.7168, lng: -95.4110 },
  { name: "Chloe Dao Boutique", category: "shopping", subcategory: "Designer Fashion", address: "2506 Rice Blvd, Houston, TX 77005", description: "Project Runway winner's boutique with original designs and custom alterations.", website: "https://www.chloedao.com", phone: "(713) 521-5765", lat: 29.7157, lng: -95.4101 },
  { name: "Crossroads Trading", category: "shopping", subcategory: "Resale", address: "2524 University Blvd, Houston, TX 77005", description: "Buy, sell, and trade trendy secondhand clothing and accessories.", website: "https://www.crossroadstrading.com", phone: "(713) 942-8154", lat: 29.7169, lng: -95.4102 },
  { name: "Fig Tree Accessories", category: "shopping", subcategory: "Accessories", address: "2434 University Blvd, Houston, TX 77005", description: "Stylish accessories, jewelry, handbags, and fashion-forward finds.", website: "", phone: "(713) 524-0807", lat: 29.7163, lng: -95.4120 },
  { name: "francesca's", category: "shopping", subcategory: "Boutique", address: "2514 University Blvd, Houston, TX 77005", description: "Trendy boutique with affordable clothing, jewelry, and home decor.", website: "https://www.francescas.com", phone: "(713) 523-6359", lat: 29.7168, lng: -95.4108 },
  { name: "Gap", category: "shopping", subcategory: "Fashion", address: "2520 University Blvd, Houston, TX 77005", description: "Classic American casual wear for the whole family.", website: "https://www.gap.com", phone: "(713) 522-3688", lat: 29.7169, lng: -95.4104 },
  { name: "Hemline Rice Village", category: "shopping", subcategory: "Women's Fashion", address: "2440 University Blvd, Houston, TX 77005", description: "Southern women's boutique with trendy, affordable fashion and accessories.", website: "https://www.hemlineboutique.com", phone: "(713) 621-1918", lat: 29.7163, lng: -95.4115 },
  { name: "Jos A. Bank", category: "shopping", subcategory: "Men's Fashion", address: "2505 University Blvd, Houston, TX 77005", description: "Classic men's suits, dress shirts, and professional attire.", website: "https://www.josbank.com", phone: "(713) 529-9449", lat: 29.7166, lng: -95.4117 },
  { name: "Kissue", category: "shopping", subcategory: "Boutique", address: "2444 University Blvd, Houston, TX 77005", description: "Unique boutique with trendy clothing, accessories, and lifestyle goods.", website: "https://www.kissue.com", phone: "(713) 521-0908", lat: 29.7163, lng: -95.4113 },
  { name: "Lily Rain", category: "shopping", subcategory: "Women's Fashion", address: "2424 University Blvd, Houston, TX 77005", description: "Contemporary women's boutique with curated seasonal collections.", website: "https://www.lilyrain.com", phone: "(713) 521-8811", lat: 29.7164, lng: -95.4122 },
  { name: "LOFT", category: "shopping", subcategory: "Women's Fashion", address: "2510 University Blvd, Houston, TX 77005", description: "Casual-chic women's clothing with modern, relaxed styles for every occasion.", website: "https://www.loft.com", phone: "(713) 524-5445", lat: 29.7168, lng: -95.4109 },
  { name: "Luxe Optical", category: "shopping", subcategory: "Eyewear", address: "2506 University Blvd, Houston, TX 77005", description: "Premium eyewear boutique with designer frames and expert lens fitting.", website: "https://www.luxeoptical.com", phone: "(713) 839-0888", lat: 29.7168, lng: -95.4113 },
  { name: "Men's Resale by the Village", category: "shopping", subcategory: "Men's Resale", address: "2438 University Blvd, Houston, TX 77005", description: "Curated resale shop for quality men's clothing and accessories.", website: "", phone: "(713) 523-2425", lat: 29.7162, lng: -95.4118 },
  { name: "Norton Ditto", category: "shopping", subcategory: "Men's Fashion", address: "2425 Rice Blvd, Houston, TX 77005", description: "Fine men's clothier with classic suits, casual wear, and expert tailoring since 1908.", website: "https://www.nortonditto.com", phone: "(713) 688-9800", lat: 29.7153, lng: -95.4118 },
  { name: "Osky & Chelle", category: "shopping", subcategory: "Boutique", address: "2428 University Blvd, Houston, TX 77005", description: "Local boutique offering unique clothing, accessories, and artisan goods.", website: "", phone: "(713) 523-2100", lat: 29.7164, lng: -95.4121 },
  { name: "Piermarini Houston", category: "shopping", subcategory: "Italian Fashion", address: "2440 Times Blvd, Houston, TX 77005", description: "Italian luxury fashion with curated European designer collections.", website: "https://www.piermarinihouston.com", phone: "(713) 523-5535", lat: 29.7150, lng: -95.4114 },
  { name: "Plato's Closet", category: "shopping", subcategory: "Resale", address: "5216 Buffalo Speedway, Houston, TX 77005", description: "Buy and sell gently used teen and young adult clothing and accessories.", website: "https://www.platoscloset.com", phone: "(713) 665-1075", lat: 29.7176, lng: -95.4178 },
  { name: "premiumgoods.", category: "shopping", subcategory: "Streetwear", address: "2416 Times Blvd, Houston, TX 77005", description: "Iconic Houston streetwear and sneaker boutique with exclusive drops.", website: "https://www.premiumgoods.net", phone: "(713) 523-5553", lat: 29.7149, lng: -95.4119 },
  { name: "Ross Dress for Less", category: "shopping", subcategory: "Discount", address: "5115 Buffalo Speedway, Houston, TX 77005", description: "Off-price retailer with discounted brand-name clothing and home goods.", website: "https://www.rossstores.com", phone: "(713) 630-0095", lat: 29.7180, lng: -95.4182 },
  { name: "Talbots", category: "shopping", subcategory: "Women's Fashion", address: "2520 University Blvd, Houston, TX 77005", description: "Timeless women's clothing with classic styles for every occasion.", website: "https://www.talbots.com", phone: "(713) 526-5557", lat: 29.7169, lng: -95.4105 },
  { name: "tasc Performance", category: "shopping", subcategory: "Activewear", address: "2510 Rice Blvd, Houston, TX 77005", description: "Bamboo-based performance wear that's comfortable, sustainable, and stylish.", website: "https://www.tascperformance.com", phone: "(713) 487-4340", lat: 29.7157, lng: -95.4099 },
  { name: "The Briar Shoppe", category: "shopping", subcategory: "Tobacco", address: "2412 Times Blvd, Houston, TX 77005", description: "Premium cigars, pipes, tobacco, and accessories in a classic setting.", website: "https://www.thebriarshoppe.com", phone: "(713) 529-6347", lat: 29.7149, lng: -95.4121 },
  { name: "The Hive", category: "shopping", subcategory: "Pop-Up", address: "2424 University Blvd, Houston, TX 77005", description: "Rotating pop-up collective featuring local designers and artisan vendors.", website: "https://www.thehivehouston.com", phone: "(713) 524-2010", lat: 29.7164, lng: -95.4123 },
  { name: "The Impeccable Pig", category: "shopping", subcategory: "Women's Fashion", address: "2430 University Blvd, Houston, TX 77005", description: "Fun, affordable women's boutique with trendy styles and gift items.", website: "https://www.theimpeccablepig.com", phone: "(713) 521-2744", lat: 29.7163, lng: -95.4121 },
  { name: "Tres Chic", category: "shopping", subcategory: "Boutique", address: "2418 University Blvd, Houston, TX 77005", description: "Chic boutique with a curated mix of clothing, jewelry, and home accents.", website: "", phone: "(713) 522-7983", lat: 29.7164, lng: -95.4125 },
  { name: "White House Black Market", category: "shopping", subcategory: "Women's Fashion", address: "2534 University Blvd, Houston, TX 77005", description: "Sophisticated women's fashion in a signature black and white palette.", website: "https://www.whitehouseblackmarket.com", phone: "(713) 526-1212", lat: 29.7170, lng: -95.4097 },

  // ============================================
  // MUSEUMS & CULTURAL INSTITUTIONS
  // ============================================
  { name: "Menil Collection", category: "museum", subcategory: "Art Museum", address: "1533 Sul Ross St, Houston, TX 77006", description: "World-renowned free art museum with an extraordinary collection spanning antiquity to contemporary.", website: "https://www.menil.org", phone: "(713) 525-9400", lat: 29.7372, lng: -95.3973 },
  { name: "Museum of Fine Arts, Houston", category: "museum", subcategory: "Art Museum", address: "1001 Bissonnet St, Houston, TX 77005", description: "One of the largest art museums in the US with an encyclopedic collection of over 70,000 works.", website: "https://www.mfah.org", phone: "(713) 639-7300", lat: 29.7256, lng: -95.3908 },
  { name: "Contemporary Arts Museum Houston", category: "museum", subcategory: "Art Museum", address: "5216 Montrose Blvd, Houston, TX 77006", description: "Non-collecting museum presenting the best in contemporary art with rotating exhibitions.", website: "https://www.camh.org", phone: "(713) 284-8250", lat: 29.7264, lng: -95.3917 },
  { name: "Rothko Chapel", category: "museum", subcategory: "Chapel & Art", address: "3900 Yupon St, Houston, TX 77006", description: "Non-denominational chapel featuring 14 monumental Mark Rothko paintings. A sacred space for meditation.", website: "https://www.rothkochapel.org", phone: "(713) 524-9839", lat: 29.7375, lng: -95.3960 },
  { name: "Children's Museum Houston", category: "museum", subcategory: "Children's Museum", address: "1500 Binz St, Houston, TX 77004", description: "Interactive exhibits designed to inspire children to explore science, technology, and culture.", website: "https://www.cmhouston.org", phone: "(713) 522-1138", lat: 29.7218, lng: -95.3855 },
  { name: "Houston Museum of Natural Science", category: "museum", subcategory: "Natural Science", address: "5555 Hermann Park Dr, Houston, TX 77030", description: "Permanent exhibits on dinosaurs, gems, space, and wildlife with a planetarium and butterfly center.", website: "https://www.hmns.org", phone: "(713) 639-4629", lat: 29.7221, lng: -95.3896 },
  { name: "Holocaust Museum Houston", category: "museum", subcategory: "History Museum", address: "5401 Caroline St, Houston, TX 77004", description: "Powerful museum dedicated to educating about the Holocaust and combating prejudice.", website: "https://www.hmh.org", phone: "(713) 942-8000", lat: 29.7228, lng: -95.3863 },
  { name: "Asia Society Texas Center", category: "museum", subcategory: "Cultural Center", address: "1370 Southmore Blvd, Houston, TX 77004", description: "Cultural institution promoting understanding between Asia and the West through art and programs.", website: "https://asiasociety.org/texas", phone: "(713) 496-9901", lat: 29.7245, lng: -95.3842 },
  { name: "Burke Baker Planetarium", category: "museum", subcategory: "Planetarium", address: "5555 Hermann Park Dr, Houston, TX 77030", description: "State-of-the-art planetarium with immersive shows about space and astronomy.", website: "https://www.hmns.org/planetarium", phone: "(713) 639-4629", lat: 29.7220, lng: -95.3898 },
  { name: "Cockrell Butterfly Center", category: "museum", subcategory: "Natural Science", address: "5555 Hermann Park Dr, Houston, TX 77030", description: "Three-story glass habitat with thousands of live butterflies and a 50-foot waterfall.", website: "https://www.hmns.org/cockrell-butterfly-center", phone: "(713) 639-4629", lat: 29.7219, lng: -95.3894 },
  { name: "Color Factory Houston", category: "museum", subcategory: "Interactive Museum", address: "2505 Dunlavy St, Houston, TX 77006", description: "Interactive art experience with colorful rooms, installations, and shareable moments.", website: "https://www.colorfactory.co/houston", phone: "(832) 476-4700", lat: 29.7380, lng: -95.3990 },
  { name: "Cy Twombly Gallery", category: "museum", subcategory: "Art Gallery", address: "1501 Branard St, Houston, TX 77006", description: "Renzo Piano-designed gallery dedicated to the works of Cy Twombly.", website: "https://www.menil.org", phone: "(713) 525-9400", lat: 29.7370, lng: -95.3968 },
  { name: "Blaffer Art Museum", category: "museum", subcategory: "Art Museum", address: "4173 Elgin St, Houston, TX 77204", description: "University of Houston's fine art museum with contemporary exhibitions.", website: "https://www.blafferartmuseum.org", phone: "(713) 743-9521", lat: 29.7230, lng: -95.3430 },
  { name: "Buffalo Soldiers National Museum", category: "museum", subcategory: "History Museum", address: "3816 Caroline St, Houston, TX 77004", description: "Museum honoring the legacy of African American soldiers from the Civil War to present.", website: "https://www.buffalosoldiermuseum.com", phone: "(713) 942-8920", lat: 29.7282, lng: -95.3845 },
  { name: "Czech Center Museum Houston", category: "museum", subcategory: "Cultural Museum", address: "4920 San Jacinto St, Houston, TX 77004", description: "Museum celebrating Czech and Slovak heritage with art, artifacts, and cultural programs.", website: "https://www.czechcenter.org", phone: "(713) 349-0339", lat: 29.7185, lng: -95.3810 },
  { name: "Dan Flavin Installation at Richmond Hall", category: "museum", subcategory: "Art Installation", address: "1504 Richmond Ave, Houston, TX 77006", description: "Permanent site-specific fluorescent light installation by minimalist artist Dan Flavin.", website: "https://www.menil.org", phone: "(713) 525-9400", lat: 29.7358, lng: -95.3955 },
  { name: "DeBakey Library and Museum", category: "museum", subcategory: "Medical Museum", address: "6565 Fannin St, Houston, TX 77030", description: "Museum honoring pioneering heart surgeon Michael DeBakey's contributions to medicine.", website: "https://www.bcm.edu", phone: "(713) 798-4951", lat: 29.7108, lng: -95.3965 },
  { name: "DiverseWorks", category: "museum", subcategory: "Art Space", address: "4102 Fannin St, Houston, TX 77004", description: "Nonprofit art space presenting new, experimental visual and performing arts.", website: "https://www.diverseworks.org", phone: "(713) 223-8346", lat: 29.7288, lng: -95.3855 },
  { name: "Art Car Museum", category: "museum", subcategory: "Specialty Museum", address: "140 Heights Blvd, Houston, TX 77007", description: "Free museum showcasing Houston's famous art car culture and outsider art.", website: "https://www.artcarmuseum.com", phone: "(713) 861-5526", lat: 29.7720, lng: -95.3880 },
  { name: "Bayou Bend Collection and Gardens", category: "museum", subcategory: "Historic Estate", address: "6003 Memorial Dr, Houston, TX 77007", description: "Museum of Fine Arts estate with American decorative arts and stunning gardens.", website: "https://www.mfah.org", phone: "(713) 639-7750", lat: 29.7620, lng: -95.4230 },
  { name: "Houston Center for Contemporary Craft", category: "museum", subcategory: "Craft Museum", address: "4848 Main St, Houston, TX 77002", description: "Museum dedicated to contemporary craft with exhibitions, studios, and a retail gallery.", website: "https://www.crafthouston.org", phone: "(713) 529-4848", lat: 29.7310, lng: -95.3830 },
  { name: "Houston Center for Photography", category: "museum", subcategory: "Photography", address: "1441 W Alabama St, Houston, TX 77006", description: "Nonprofit photography center with exhibitions, workshops, and artist programs.", website: "https://www.hcponline.org", phone: "(713) 529-4755", lat: 29.7395, lng: -95.3920 },
  { name: "Lawndale Art Center", category: "museum", subcategory: "Art Center", address: "4912 Main St, Houston, TX 77002", description: "Free contemporary art center with exhibitions, performances, and community events.", website: "https://www.lawndaleartcenter.org", phone: "(713) 528-5858", lat: 29.7305, lng: -95.3828 },
  { name: "McClain Gallery", category: "museum", subcategory: "Art Gallery", address: "2242 Richmond Ave, Houston, TX 77098", description: "Fine art gallery representing contemporary artists with rotating exhibitions.", website: "https://www.mcclaingallery.com", phone: "(713) 520-9988", lat: 29.7186, lng: -95.4158 },
  { name: "Menil Drawing Institute", category: "museum", subcategory: "Art Museum", address: "1412 W Main St, Houston, TX 77006", description: "Dedicated space for the exhibition and study of modern and contemporary drawing.", website: "https://www.menil.org", phone: "(713) 525-9400", lat: 29.7368, lng: -95.3970 },
  { name: "The Health Museum", category: "museum", subcategory: "Science Museum", address: "1515 Hermann Dr, Houston, TX 77004", description: "Interactive museum exploring the human body, health, and medical science.", website: "https://www.thehealthmuseum.org", phone: "(713) 521-1515", lat: 29.7225, lng: -95.3860 },
  { name: "The Heritage Society Museum", category: "museum", subcategory: "History Museum", address: "1100 Bagby St, Houston, TX 77002", description: "Preserving Houston history with historic structures, artifacts, and walking tours.", website: "https://www.heritagesociety.org", phone: "(713) 655-1912", lat: 29.7590, lng: -95.3700 },
  { name: "The Houston Fire Museum", category: "museum", subcategory: "History Museum", address: "2403 Milam St, Houston, TX 77006", description: "Museum in a 1899 firehouse showcasing Houston's firefighting history.", website: "https://www.houstonfiremuseum.org", phone: "(713) 524-2526", lat: 29.7500, lng: -95.3720 },
  { name: "The Printing Museum", category: "museum", subcategory: "Specialty Museum", address: "1324 W Clay St, Houston, TX 77019", description: "Museum celebrating the art and history of printing with hands-on demonstrations.", website: "https://www.printingmuseum.org", phone: "(713) 522-4652", lat: 29.7530, lng: -95.3910 },
  { name: "Houston Museum of African American Culture", category: "museum", subcategory: "Cultural Museum", address: "4807 Caroline St, Houston, TX 77004", description: "Celebrating African American art, history, and culture through exhibitions and programs.", website: "https://www.hmaac.org", phone: "(713) 526-1015", lat: 29.7310, lng: -95.3840 },
  { name: "Houston Police Museum", category: "museum", subcategory: "History Museum", address: "1200 Travis St, Houston, TX 77002", description: "Museum featuring the history and evolution of the Houston Police Department.", website: "https://www.houstonpolicemuseum.org", phone: "(713) 308-1200", lat: 29.7550, lng: -95.3620 },
  { name: "Station Museum of Contemporary Art", category: "museum", subcategory: "Art Museum", address: "1502 Alabama St, Houston, TX 77004", description: "Free museum presenting socially engaged contemporary art exhibitions.", website: "https://www.stationmuseum.com", phone: "(713) 529-6900", lat: 29.7390, lng: -95.3870 },
  { name: "TFTI Houston", category: "museum", subcategory: "Interactive Museum", address: "218 Tremont St, Houston, TX 77006", description: "Interactive selfie museum with colorful rooms and Instagram-worthy installations.", website: "https://www.tftihouston.com", phone: "(281) 974-5337", lat: 29.7400, lng: -95.3850 },
  { name: "The Graffiti & Street Art Museum of Texas", category: "museum", subcategory: "Art Museum", address: "2010 Leeland St, Houston, TX 77003", description: "Museum celebrating street art and graffiti culture with rotating murals and exhibitions.", website: "https://www.graffitiarttexas.com", phone: "", lat: 29.7440, lng: -95.3580 },
  { name: "Cullen Sculpture Garden", category: "museum", subcategory: "Sculpture Garden", address: "5101 Montrose Blvd, Houston, TX 77006", description: "Isamu Noguchi-designed outdoor sculpture garden with major works of modern and contemporary art.", website: "https://www.mfah.org", phone: "(713) 639-7300", lat: 29.7262, lng: -95.3915 },
  { name: "Rienzi", category: "museum", subcategory: "Historic Estate", address: "1406 Kirby Dr, Houston, TX 77019", description: "Museum of Fine Arts house museum featuring European decorative arts and stunning gardens.", website: "https://www.mfah.org", phone: "(713) 639-7800", lat: 29.7480, lng: -95.4050 },
  { name: "Museum of Southern History", category: "museum", subcategory: "History Museum", address: "7502 Fondren Rd, Houston, TX 77074", description: "Museum dedicated to the history and heritage of the American South.", website: "https://www.museumofsouthernhistory.com", phone: "(281) 489-1861", lat: 29.6950, lng: -95.5070 },

  // ============================================
  // ADDITIONAL LISTINGS (from rice-village.com)
  // ============================================

  // Dining
  { name: "Badolina Bakery & Cafe", category: "restaurant", subcategory: "Bakery & Cafe", address: "5555 Morningside Drive, Houston, TX 77005", description: "Artisan bakery and cafe serving fresh-baked breads, pastries, sandwiches, and specialty coffee.", website: "https://www.badolina.com", phone: "(346) 230-5765", lat: 29.7153, lng: -95.4143 },
  { name: "Bluestone Lane", category: "coffee", subcategory: "Coffee & Cafe", address: "2414 University Blvd, Houston, TX 77005", description: "Australian-inspired artisanal coffee shop and cafe with premium brews, avocado toast, and light bites.", website: "https://www.bluestonelane.com", phone: "(718) 374-6858", lat: 29.7169, lng: -95.4118 },
  { name: "Hudson House", category: "restaurant", subcategory: "Seafood", address: "2414 University Blvd, Suite 100, Houston, TX 77005", description: "Fresh seafood restaurant with an elegant New England-inspired atmosphere and raw bar.", website: "https://www.hudsonhouserestaurant.com", phone: "(713) 526-0438", lat: 29.7169, lng: -95.4117 },
  { name: "Jeni's Ice Creams", category: "restaurant", subcategory: "Ice Cream", address: "5411 Morningside Drive, Houston, TX 77005", description: "Artisanal ice cream shop known for creative, chef-driven flavors made with grass-grazed milk.", website: "https://www.jenis.com", phone: "(713) 597-6767", lat: 29.7155, lng: -95.4147 },
  { name: "Navy Blue", category: "restaurant", subcategory: "Seafood", address: "2445 Times Blvd, Houston, TX 77005", description: "Upscale seafood restaurant with a modern coastal atmosphere, raw bar, and craft cocktails.", website: "https://www.navybluehtx.com", phone: "(713) 485-5498", lat: 29.7149, lng: -95.4113 },
  { name: "Shake Shack", category: "restaurant", subcategory: "Burgers", address: "6205 Kirby Dr, Houston, TX 77005", description: "Modern roadside burger stand serving gourmet ShackBurgers, crinkle-cut fries, and frozen custard.", website: "https://www.shakeshack.com", phone: "(346) 318-2083", lat: 29.7185, lng: -95.4120 },
  { name: "The Rice Box", category: "restaurant", subcategory: "Chinese", address: "5504 Morningside Drive, Houston, TX 77005", description: "Chinese-American comfort food featuring rice boxes, stir-fries, and signature dishes to go.", website: "https://www.thericebox.com", phone: "(713) 528-2888", lat: 29.7156, lng: -95.4144 },
  { name: "Van Leeuwen", category: "restaurant", subcategory: "Ice Cream", address: "2565 Amherst St, Houston, TX 77005", description: "Artisan ice cream crafted from high-quality, feel-good ingredients with classic and vegan options.", website: "https://www.vanleeuwenicecream.com", phone: "(346) 331-8221", lat: 29.7160, lng: -95.4105 },
  { name: "Sprinkles", category: "restaurant", subcategory: "Bakery", address: "2540 University Blvd, Houston, TX 77005", description: "Iconic cupcake bakery offering handcrafted cupcakes, cookies, and layer cakes in gourmet flavors.", website: "https://www.sprinkles.com", phone: "(713) 871-9524", lat: 29.7170, lng: -95.4100 },
  { name: "Hopdoddy Burger Bar", category: "restaurant", subcategory: "Burgers", address: "5510 Morningside Dr, Suite 100, Houston, TX 77005", description: "Eco-minded craft burger bar with house-ground patties, hand-cut fries, and local craft beer.", website: "https://www.hopdoddy.com", phone: "(713) 352-3825", lat: 29.7154, lng: -95.4145 },

  // Shopping & Retail
  { name: "CB2", category: "shopping", subcategory: "Modern Furniture", address: "2414 University Blvd #130, Houston, TX 77005", description: "Modern furniture and home decor from Crate & Barrel's contemporary lifestyle brand.", website: "https://www.cb2.com", phone: "(713) 526-2200", lat: 29.7169, lng: -95.4119 },
  { name: "Lovesac", category: "shopping", subcategory: "Modern Furniture", address: "2510 University Blvd, Houston, TX 77005", description: "Innovative furniture company known for modular Sactionals sofas and Sacs bean bags.", website: "https://www.lovesac.com", phone: "(713) 526-7622", lat: 29.7168, lng: -95.4107 },
  { name: "Paper Source", category: "shopping", subcategory: "Stationery & Gifts", address: "5515 Kelvin Drive #100, Houston, TX 77005", description: "Specialty retailer of fine paper goods, greeting cards, gift wrap, and unique gifts.", website: "https://www.papersource.com", phone: "(713) 529-0340", lat: 29.7152, lng: -95.4138 },
  { name: "West Elm", category: "shopping", subcategory: "Modern Furniture", address: "2501 University Blvd, Houston, TX 77005", description: "Modern furniture, home accessories, and decor with mid-century, modern, and sustainable design.", website: "https://www.westelm.com", phone: "(713) 579-0058", lat: 29.7166, lng: -95.4110 },
  { name: "Birkenstock", category: "shopping", subcategory: "Footwear", address: "2503 Amherst St, Suite 121, Houston, TX 77005", description: "Iconic German footwear brand known for contoured cork footbed sandals and comfortable shoes.", website: "https://www.birkenstock.com", phone: "(713) 522-0498", lat: 29.7162, lng: -95.4108 },
  { name: "Duck Camp", category: "shopping", subcategory: "Outdoor Goods", address: "5510 Morningside Dr, Suite 170, Houston, TX 77005", description: "Premium outdoor goods and technical apparel designed for hunting, fishing, and outdoor pursuits.", website: "https://www.duckcamp.com", phone: "(713) 999-0442", lat: 29.7154, lng: -95.4146 },
  { name: "Golden Gray", category: "shopping", subcategory: "Women's Clothing", address: "2511 University Blvd, Houston, TX 77005", description: "Curated women's boutique offering contemporary clothing, accessories, and jewelry.", website: "https://www.goldengray.com", phone: "(713) 364-8590", lat: 29.7166, lng: -95.4109 },
  { name: "Gorjana", category: "shopping", subcategory: "Jewelry", address: "2552 University Blvd, Houston, TX 77005", description: "California-inspired jewelry brand offering delicate, layerable gold and silver pieces.", website: "https://www.gorjana.com", phone: "(713) 955-2270", lat: 29.7170, lng: -95.4098 },
  { name: "Kemo Sabe", category: "shopping", subcategory: "Western Wear", address: "2414 University Blvd, Suite 180, Houston, TX 77005", description: "High-end Western wear featuring custom cowboy hats, boots, and turquoise jewelry.", website: "https://www.kemosabe.com", phone: "(713) 955-4200", lat: 29.7169, lng: -95.4116 },
  { name: "KREWE", category: "shopping", subcategory: "Eyewear", address: "5515 Kelvin Drive #125, Houston, TX 77005", description: "New Orleans-born handcrafted eyewear brand with bold, fashion-forward frames.", website: "https://www.krewe.com", phone: "(713) 955-2185", lat: 29.7152, lng: -95.4137 },
  { name: "Lululemon Athletica", category: "shopping", subcategory: "Activewear", address: "2560 University Blvd, Houston, TX 77005", description: "Premium athletic apparel for yoga, running, and training with a focus on innovation and community.", website: "https://www.lululemon.com", phone: "(713) 521-0770", lat: 29.7171, lng: -95.4096 },
  { name: "Luminary", category: "shopping", subcategory: "Women's Fashion", address: "2556 University Blvd, Houston, TX 77005", description: "Women's fashion boutique featuring curated contemporary clothing and lifestyle pieces.", website: "https://www.shopluminary.com", phone: "(713) 364-8573", lat: 29.7171, lng: -95.4097 },
  { name: "Mizzen+Main", category: "shopping", subcategory: "Men's Clothing", address: "2548 University Blvd, Houston, TX 77005", description: "Performance menswear brand offering dress shirts and apparel with moisture-wicking, stretch fabrics.", website: "https://www.mizzenandmain.com", phone: "(713) 955-2125", lat: 29.7170, lng: -95.4099 },
  { name: "On", category: "shopping", subcategory: "Athletic Wear", address: "6225 Kirby Dr, Houston, TX 77005", description: "Swiss-engineered performance running shoes and athletic apparel with CloudTec cushioning technology.", website: "https://www.on.com", phone: "(713) 489-5270", lat: 29.7186, lng: -95.4121 },
  { name: "ParkerJoe", category: "shopping", subcategory: "Children's Clothing", address: "5515 Kelvin Drive, Suite 95, Houston, TX 77005", description: "Children's clothing, toys, and gifts boutique with curated collections for babies and kids.", website: "https://www.parkerjoe.com", phone: "(713) 955-2260", lat: 29.7152, lng: -95.4139 },
  { name: "Studs", category: "shopping", subcategory: "Piercing Studio", address: "2567 Amherst St, Houston, TX 77005", description: "Modern ear piercing studio offering professional piercings and curated earring collections.", website: "https://www.studs.com", phone: "(713) 955-2255", lat: 29.7161, lng: -95.4103 },
  { name: "Sunglass Hut", category: "shopping", subcategory: "Sunglasses", address: "2507 Amherst St, Houston, TX 77005", description: "Leading sunglass retailer with designer brands including Ray-Ban, Oakley, and Prada.", website: "https://www.sunglasshut.com", phone: "(713) 524-1488", lat: 29.7162, lng: -95.4107 },
  { name: "Tecovas", category: "shopping", subcategory: "Boots", address: "2400 University Blvd, Suite 100, Houston, TX 77005", description: "Handcrafted Western boots and accessories made from premium leathers in Leon, Mexico.", website: "https://www.tecovas.com", phone: "(713) 955-2100", lat: 29.7165, lng: -95.4125 },
  { name: "The Beaufort Bonnet Company", category: "shopping", subcategory: "Baby & Children's", address: "5515 Kelvin Drive, Suite 120, Houston, TX 77005", description: "Baby and children's clothing brand known for timeless, beautifully crafted bonnets and apparel.", website: "https://www.thebeaufortbonnetcompany.com", phone: "(713) 955-2280", lat: 29.7152, lng: -95.4136 },
  { name: "Vuori", category: "shopping", subcategory: "Activewear", address: "5515 Kelvin Drive, Suite 90, Houston, TX 77005", description: "California-inspired activewear and apparel blending performance with a coastal lifestyle aesthetic.", website: "https://www.vuoriclothing.com", phone: "(713) 955-2150", lat: 29.7152, lng: -95.4140 },
  { name: "Warby Parker", category: "shopping", subcategory: "Eyewear", address: "2518 University Blvd, Houston, TX 77005", description: "Fashion-forward prescription eyeglasses and sunglasses with home try-on and in-store styling.", website: "https://www.warbyparker.com", phone: "(713) 489-4572", lat: 29.7168, lng: -95.4106 },

  // Beauty, Health & Services
  { name: "24 Hour Fitness", category: "shopping", subcategory: "Fitness Center", address: "2500 Dunstan Rd, Houston, TX 77005", description: "Full-service fitness center with state-of-the-art equipment, group classes, and personal training.", website: "https://www.24hourfitness.com", phone: "(713) 524-9191", lat: 29.7163, lng: -95.4112 },
  { name: "Bluemercury", category: "shopping", subcategory: "Skincare & Beauty", address: "2506 University Blvd, Houston, TX 77005", description: "Luxury beauty retailer offering curated skincare, cosmetics, and spa-quality treatments.", website: "https://www.bluemercury.com", phone: "(713) 526-0045", lat: 29.7167, lng: -95.4108 },
  { name: "Clique Salon", category: "shopping", subcategory: "Hair Salon", address: "2414 Times Blvd, Suite 120, Houston, TX 77005", description: "Luxury hair salon providing expert cuts, color, styling, and personalized beauty services.", website: "https://www.cliquesalon.com", phone: "(713) 521-4247", lat: 29.7150, lng: -95.4115 },
  { name: "Drybar", category: "shopping", subcategory: "Blowout Bar", address: "2519 Amherst St, Houston, TX 77005", description: "Blowout-only hair salon offering signature styles, treatments, and a fun, social atmosphere.", website: "https://www.thedrybar.com", phone: "(713) 999-0650", lat: 29.7162, lng: -95.4106 },
  { name: "GLO30", category: "shopping", subcategory: "Skincare", address: "2509 Amherst St, Houston, TX 77005", description: "Membership-based skincare studio offering customized facials and skin health treatments.", website: "https://www.glo30.com", phone: "(713) 489-5610", lat: 29.7162, lng: -95.4107 },
  { name: "Kelsey-Seybold Clinic", category: "shopping", subcategory: "Health Clinic", address: "2414 University Blvd, Suite 200, Houston, TX 77005", description: "Multispecialty physician group providing comprehensive women's health and wellness services.", website: "https://www.kelsey-seybold.com", phone: "(713) 442-0000", lat: 29.7169, lng: -95.4120 },
  { name: "MAC Cosmetics", category: "shopping", subcategory: "Beauty & Makeup", address: "2411 Times Blvd, Suite 130, Houston, TX 77005", description: "Professional-quality cosmetics brand known for bold colors, artistry tools, and inclusivity.", website: "https://www.maccosmetics.com", phone: "(713) 524-2840", lat: 29.7149, lng: -95.4116 },
  { name: "Madison Reed", category: "shopping", subcategory: "Hair Color Bar", address: "2515 Amherst St #A126, Houston, TX 77005", description: "Hair color bar offering salon-quality, ammonia-free hair color services and products.", website: "https://www.madison-reed.com", phone: "(713) 999-0480", lat: 29.7162, lng: -95.4105 },
  { name: "Sephora", category: "shopping", subcategory: "Beauty & Cosmetics", address: "2401 Times Blvd, Suite 150, Houston, TX 77005", description: "Leading beauty retailer with an unrivaled selection of prestige skincare, makeup, and fragrance.", website: "https://www.sephora.com", phone: "(713) 526-0850", lat: 29.7149, lng: -95.4118 },
  { name: "SkinSpirit", category: "shopping", subcategory: "Med Spa", address: "2401 Times Blvd, Suite 110, Houston, TX 77005", description: "Expert-led medi-spa offering facials, injectables, laser treatments, and skin rejuvenation.", website: "https://www.skinspirit.com", phone: "(713) 955-4460", lat: 29.7149, lng: -95.4119 },
  { name: "Solidcore", category: "shopping", subcategory: "Fitness Studio", address: "2411 Times Blvd, Houston, TX 77005", description: "High-intensity Pilates-inspired workout studio using the signature Sweatlana reformer machine.", website: "https://www.solidcore.co", phone: "(713) 955-4470", lat: 29.7149, lng: -95.4117 },
  { name: "Sugared + Bronzed", category: "shopping", subcategory: "Beauty Services", address: "2401 Times Blvd, Suite 100, Houston, TX 77005", description: "Sugaring hair removal and airbrush tanning studio for a smooth, sun-kissed look year-round.", website: "https://www.sugaredandbronzed.com", phone: "(713) 955-2290", lat: 29.7149, lng: -95.4120 },
  { name: "Face Haus", category: "shopping", subcategory: "Skincare", address: "2414 University Blvd, Houston, TX 77005", description: "Express facial bar offering quick, affordable, and customized skincare treatments.", website: "https://www.facehaus.com", phone: "(713) 955-2295", lat: 29.7169, lng: -95.4118 },
  { name: "Beautique", category: "shopping", subcategory: "Beauty Salon", address: "2414 University Blvd, Houston, TX 77005", description: "Full-service beauty salon offering hair, nails, and aesthetic treatments in a chic setting.", website: "https://www.beautiquehouston.com", phone: "(713) 528-0799", lat: 29.7169, lng: -95.4117 }
];

// Image mapping — listing name → image file path
const imageMap = {
  // Restaurants
  "The Rice Box": "restaurants/the-rice-box.jpg",
  "Cochinita & Co.": "restaurants/cochinita-and-co.jpg",
  "Highly Recommended": "restaurants/highly-recommended.jpg",
  "Jason's Deli": "restaurants/jasons-deli.jpg",
  "The Bistro": "restaurants/the-bistro.jpg",
  "Badolina Bakery & Cafe": "restaurants/badolina-bakery.jpg",
  "Hudson House": "restaurants/hudson-house.jpg",
  "Jeni's Ice Creams": "restaurants/jenis-ice-creams.jpg",
  "Navy Blue": "restaurants/navy-blue.jpg",
  "Shake Shack": "restaurants/shake-shack.jpg",
  "Van Leeuwen": "restaurants/van-leeuwen.jpg",
  "Sprinkles": "restaurants/sprinkles.jpg",
  "Hopdoddy Burger Bar": "restaurants/hopdoddy.jpg",
  "Torchy's Tacos": "restaurants/torchys-tacos.jpg",
  "Antonios Mexican Grille": "restaurants/antonios-mexican-grille.jpg",
  "Azuma": "restaurants/azuma.jpg",
  "Black Walnut Cafe": "restaurants/black-walnut-cafe.jpg",
  "Bronson's House": "restaurants/bronsons-house.jpg",
  "Brown Bag Deli": "restaurants/brown-bag-deli.jpg",
  "Buca di Beppo": "restaurants/buca-di-beppo.jpg",
  "Cafe Rabelais": "restaurants/cafe-rabelais.jpg",
  "Candelari's": "restaurants/candelaris.jpg",
  "Chipotle Mexican Grill": "restaurants/chipotle.jpg",
  "CiCi's Pizza": "restaurants/cicis-pizza.jpg",
  "CoCo Crepes, Waffles & Coffee": "restaurants/coco-crepes.jpg",
  "Coppa Osteria": "restaurants/coppa-osteria.jpg",
  "Cyclone Anaya's": "restaurants/cyclone-anayas.jpg",
  "D'Amico's Italian Market Cafe": "restaurants/damicos.jpg",
  "Dave's Hot Chicken": "restaurants/daves-hot-chicken.jpg",
  "El Meson": "restaurants/el-meson.jpg",
  "El Topo": "restaurants/el-topo.jpg",
  "Goode Company Hamburgers & Taqueria": "restaurants/goode-company-hamburgers.jpg",
  "Goode Company Seafood": "restaurants/goode-company-seafood.jpg",
  "Gratify": "restaurants/gratify.jpg",
  "Hamsa": "restaurants/hamsa.jpg",
  "Helen Greek Food & Wine": "restaurants/helen-greek.jpg",
  "Hillstone Restaurant": "restaurants/hillstone.jpg",
  "Hobbit Cafe": "restaurants/hobbit-cafe.jpg",
  "Hopdoddy Burger Bar": "restaurants/hopdoddy.jpg",
  "Hu's Cooking": "restaurants/hus-cooking.jpg",
  "Hungry's": "restaurants/hungrys.jpg",
  "Island Grill": "restaurants/island-grill.jpg",
  "Istanbul Grill & Deli": "restaurants/istanbul-grill.jpg",
  "Kim Son Cafe": "restaurants/kim-son-cafe.jpg",
  "KIN by Chef Evelyn": "restaurants/kin-by-chef-evelyn.jpg",
  "Kolache Factory": "restaurants/kolache-factory.jpg",
  "La Fresca Pizza": "restaurants/la-fresca-pizza.jpg",
  "Le Peep": "restaurants/le-peep.jpg",
  "Little Matt's": "restaurants/little-matts.jpg",
  "Local Foods": "restaurants/local-foods.jpg",
  "Mendocino Farms": "restaurants/mendocino-farms.jpg",
  "Miller's Cafe": "restaurants/millers-cafe.jpg",
  "Nice Sprout Cafe": "restaurants/nice-sprout.jpg",
  "Oh My Gogi": "restaurants/oh-my-gogi.jpg",
  "Pacha Nikkei": "restaurants/pacha-nikkei.jpg",
  "Pasha Turkish Restaurant": "restaurants/pasha-turkish.jpg",
  "Poblano's": "restaurants/poblanos.jpg",
  "Pokeworks": "restaurants/pokeworks.jpg",
  "Politan Row Houston": "restaurants/politan-row.jpg",
  "Prego": "restaurants/prego.jpg",
  "Prima Pasta": "restaurants/prima-pasta.jpg",
  "Roma": "restaurants/roma.jpg",
  "Safina": "restaurants/safina.jpg",
  "Salata": "restaurants/salata.jpg",
  "Salento Bistrot": "restaurants/salento-bistrot.jpg",
  "Seco's Latin Cuisine": "restaurants/secos-latin.jpg",
  "Shiva Indian Restaurant": "restaurants/shiva-indian.jpeg",
  "Southwell's Hamburger Grill": "restaurants/southwells.jpg",
  "Sweet Paris": "restaurants/sweet-paris.jpg",
  "sweetgreen": "restaurants/sweetgreen.jpg",
  "Tamashi": "restaurants/tamashi.jpg",
  "Taste of Spices": "restaurants/taste-of-spices.jpg",
  "Thai Village Restaurant": "restaurants/thai-village.jpg",
  "The Halal Guys": "restaurants/halal-guys.jpg",
  "The Lexington Grille": "restaurants/lexington-grille.jpg",
  "The Raven Grill": "restaurants/raven-grill.jpg",
  "Tiger Noodle House": "restaurants/tiger-noodle.jpg",
  "Tiny's No. 5": "restaurants/tinys-no-5.jpg",
  "True Food Kitchen": "restaurants/sweetgreen.jpg",
  "Two Guys Pizzeria": "restaurants/two-guys-pizzeria.jpg",
  "Velvet Taco": "restaurants/velvet-taco.jpg",
  "Whataburger": "restaurants/whataburger.jpg",
  "Zoe's Kitchen": "restaurants/zoes-kitchen.jpg",

  // Bars
  "Kirbside Bar": "bars/kirbside-bar.jpg",
  "Rye 51": "bars/rye-51.jpg",
  "The Tipsy Dessert Bar": "bars/tipsy-dessert-bar.jpg",
  "Anvil Bar & Refuge": "bars/anvil-bar.jpg",
  "Bacco": "bars/bacco.jpg",
  "Bar 2200": "bars/bar-2200.jpg",
  "Bar 9": "bars/bar-9.jpg",
  "Bar Esperanto": "bars/bar-esperanto.jpg",
  "Boondocks": "bars/boondocks.jpg",
  "Capone's Oven & Bar": "bars/capones.jpg",
  "Christians Tailgate": "bars/christians-tailgate.jpg",
  "Dino's Den": "bars/dinos-den.jpg",
  "Downing Street Social Club": "bars/downing-street.jpg",
  "Elie Live Music Wine Bar": "bars/elie-wine-bar.jpg",
  "Grand Prize Bar": "bars/grand-prize.jpg",
  "Kirby Ice House": "bars/kirby-ice-house.jpg",
  "La Bar": "bars/la-bar.jpg",
  "Little Woodrow's Bellaire": "bars/little-woodrows-bellaire.jpg",
  "Little Woodrow's Rice Village": "bars/little-woodrows-rv.jpg",
  "Lizzard's Pub": "bars/lizzards-pub.jpg",
  "Marquis II": "bars/marquis-ii.jpg",
  "McElroy's Pub": "bars/mcelroys-pub.jpg",
  "McGonigel's Mucky Duck": "bars/mucky-duck.jpg",
  "Olive + Twist Bar": "bars/olive-twist.jpg",
  "On The Kirb": "bars/on-the-kirb.jpg",
  "Penny Whistle Pub": "bars/penny-whistle.jpg",
  "Poison Girl": "bars/poison-girl.jpg",
  "Red Lion British Pub": "bars/red-lion.jpg",
  "Revelry on Richmond": "bars/revelry.jpg",
  "Simone on Sunset": "bars/simone-on-sunset.jpg",
  "Sixty Vines": "bars/sixty-vines.jpg",
  "T.K. Bitterman's": "bars/tk-bittermans.jpg",
  "The Cedar Bar": "bars/cellar-bar.jpg",
  "The Cellar Bar": "bars/cellar-bar.jpg",
  "The Davenport": "bars/davenport.jpg",
  "The Key": "bars/the-key.jpg",
  "The Owl": "bars/the-owl.jpg",
  "The Patio at The Pit Room": "bars/pit-room-patio.jpg",
  "The Phoenix on Westheimer": "bars/phoenix.jpg",
  "Twin Peaks Kirby": "bars/twin-peaks.jpg",
  "Under the Volcano": "bars/under-the-volcano.jpg",
  "Upstairs": "bars/upstairs.jpg",
  "Valhalla": "bars/valhalla.jpg",
  "Velvet Melvin Pub": "bars/velvet-melvin.jpg",
  "West Alabama Ice House": "bars/west-alabama-ice-house.jpg",
  "Willy's Pub": "bars/willys-pub.jpg",

  // Coffee
  "Bluestone Lane": "coffee/bluestone-lane.jpg",
  "Agnes": "coffee/agnes.jpg",
  "Agora": "coffee/agora.jpg",
  "Al Vetro": "coffee/al-vetro.jpg",
  "Anonymous Cafe": "coffee/anonymous-cafe.jpg",
  "Bebidas": "coffee/bebidas.jpg",
  "Black Hole Coffee House": "coffee/black-hole.jpg",
  "Cavo Coffee": "coffee/cavo-coffee.jpg",
  "Christo Mio": "coffee/christo-mio.jpg",
  "Common Bond Bistro & Bakery": "coffee/common-bond.jpg",
  "Cool Beans Cafe and Bakery": "coffee/cool-beans.jpg",
  "Corner Bakery Cafe": "coffee/corner-bakery.jpg",
  "Dunkin'": "coffee/dunkin.jpg",
  "Einstein Bros. Bagels": "coffee/einstein-bagels.jpg",
  "Empire Cafe": "coffee/empire-cafe.jpg",
  "Fannin Street Cafe": "coffee/fannin-street.jpg",
  "Fellini Caffe": "coffee/fellini-caffe.jpg",
  "Ginger Kale": "coffee/ginger-kale.jpg",
  "Greenway Coffee": "coffee/greenway-coffee.jpg",
  "Grinder's Coffee Bar": "coffee/grinders.jpg",
  "Honey Art Cafe": "coffee/honey-art.jpg",
  "Kaffeine Coffee": "coffee/kaffeine.jpg",
  "Luce Coffee Roasters": "coffee/luce-coffee.jpg",
  "MFA Cafe": "coffee/mfa-cafe.jpg",
  "Mictlan Coffee Roasters": "coffee/luce-coffee.jpg",
  "Panera Bread": "coffee/panera-bread.jpg",
  "Periodic Table": "coffee/periodic-table.jpg",
  "Purple Kow": "coffee/purple-kow.jpg",
  "Rice Coffeehouse": "coffee/rice-coffeehouse.jpg",
  "Rustika Cafe and Bakery": "coffee/rustika.jpg",
  "Siphon Coffee": "coffee/siphon-coffee.jpg",
  "Slowpokes": "coffee/slowpokes.jpg",
  "Starbucks": "coffee/starbucks.jpg",
  "The Chocolate Bar": "coffee/chocolate-bar.jpg",
  "The Teahouse": "coffee/teahouse.jpg",

  // Shopping
  "Kissue": "shopping/kissue.jpg",
  "Luxe Optical": "shopping/luxe-optical.jpg",
  "The Briar Shoppe": "shopping/the-briar-shoppe.jpg",
  "CB2": "shopping/cb2.jpg",
  "Lovesac": "shopping/lovesac.jpg",
  "Paper Source": "shopping/paper-source.jpg",
  "West Elm": "shopping/west-elm.jpg",
  "Birkenstock": "shopping/birkenstock.jpg",
  "Duck Camp": "shopping/duck-camp.jpg",
  "Golden Gray": "shopping/golden-gray.jpg",
  "Gorjana": "shopping/gorjana.jpg",
  "Kemo Sabe": "shopping/kemo-sabe.jpg",
  "KREWE": "shopping/krewe.jpg",
  "Lululemon Athletica": "shopping/lululemon.jpg",
  "Luminary": "shopping/luminary.jpg",
  "Mizzen+Main": "shopping/mizzen-main.jpg",
  "On": "shopping/on-running.jpg",
  "ParkerJoe": "shopping/parkerjoe.jpg",
  "Studs": "shopping/studs.jpg",
  "Sunglass Hut": "shopping/sunglass-hut.jpg",
  "Tecovas": "shopping/tecovas.jpg",
  "The Beaufort Bonnet Company": "shopping/beaufort-bonnet.jpg",
  "Vuori": "shopping/vuori.jpg",
  "Warby Parker": "shopping/warby-parker.jpg",
  "24 Hour Fitness": "shopping/24-hour-fitness.jpg",
  "Bluemercury": "shopping/bluemercury.jpg",
  "Clique Salon": "shopping/clique-salon.jpg",
  "Drybar": "shopping/drybar.jpg",
  "GLO30": "shopping/glo30.jpg",
  "Kelsey-Seybold Clinic": "shopping/kelsey-seybold.jpg",
  "MAC Cosmetics": "shopping/mac-cosmetics.jpg",
  "Madison Reed": "shopping/madison-reed.jpg",
  "Sephora": "shopping/sephora.jpg",
  "SkinSpirit": "shopping/skinspirit.jpg",
  "Solidcore": "shopping/solidcore.jpg",
  "Sugared + Bronzed": "shopping/sugared-bronzed.jpg",
  "Face Haus": "shopping/face-haus.jpg",
  "Beautique": "shopping/beautique.jpg",
  "Abejas Boutique": "shopping/abejas.jpg",
  "Altar'd State": "shopping/altard-state.jpg",
  "Ann Taylor": "shopping/ann-taylor.jpg",
  "Artisan Designs LLC": "shopping/artisan-designs.jpg",
  "Athleta": "shopping/athleta.jpg",
  "Banana Republic": "shopping/banana-republic.jpg",
  "Beehive Houston": "shopping/beehive.jpg",
  "Cariloha Bamboo": "shopping/cariloha.jpg",
  "Chloe Dao Boutique": "shopping/chloe-dao.jpg",
  "Crossroads Trading": "shopping/crossroads.jpg",
  "Fig Tree Accessories": "shopping/fig-tree.jpg",
  "francesca's": "shopping/francescas.jpg",
  "Gap": "shopping/gap.jpg",
  "Hemline Rice Village": "shopping/hemline.jpg",
  "Jos A. Bank": "shopping/jos-a-bank.jpg",
  "Lily Rain": "shopping/lily-rain.jpg",
  "LOFT": "shopping/loft.jpg",
  "Men's Resale by the Village": "shopping/mens-resale.jpg",
  "Norton Ditto": "shopping/norton-ditto.jpg",
  "Osky & Chelle": "shopping/osky-chelle.jpg",
  "Piermarini Houston": "shopping/piermarini.jpg",
  "Plato's Closet": "shopping/platos-closet.jpg",
  "premiumgoods.": "shopping/premiumgoods.jpg",
  "Ross Dress for Less": "shopping/ross.jpg",
  "Talbots": "shopping/talbots.jpg",
  "tasc Performance": "shopping/tasc-performance.jpg",
  "The Hive": "shopping/the-hive.jpg",
  "The Impeccable Pig": "shopping/impeccable-pig.jpg",
  "Tres Chic": "shopping/tres-chic.jpg",
  "White House Black Market": "shopping/white-house-black-market.jpg",

  // Museums
  "Menil Collection": "museums/menil-collection.jpg",
  "Museum of Fine Arts, Houston": "museums/mfah.jpg",
  "Contemporary Arts Museum Houston": "museums/camh.jpg",
  "Rothko Chapel": "museums/menil-collection.jpg",
  "Children's Museum Houston": "museums/childrens-museum.jpg",
  "Houston Museum of Natural Science": "museums/hmns.jpg",
  "Holocaust Museum Houston": "museums/holocaust-museum.jpg",
  "Asia Society Texas Center": "museums/asia-society.jpg",
  "Burke Baker Planetarium": "museums/burke-baker.jpg",
  "Cockrell Butterfly Center": "museums/cockrell-butterfly.jpg",
  "Color Factory Houston": "museums/color-factory.jpg",
  "Cy Twombly Gallery": "museums/cy-twombly.jpg",
  "Blaffer Art Museum": "museums/blaffer.jpg",
  "Buffalo Soldiers National Museum": "museums/buffalo-soldiers.jpg",
  "Czech Center Museum Houston": "museums/czech-center.jpg",
  "Dan Flavin Installation at Richmond Hall": "museums/dan-flavin.jpg",
  "DeBakey Library and Museum": "museums/debakey.jpg",
  "DiverseWorks": "museums/diverseworks.jpg",
  "Art Car Museum": "museums/art-car-museum.jpg",
  "Bayou Bend Collection and Gardens": "museums/bayou-bend.jpg",
  "Houston Center for Contemporary Craft": "museums/lawndale.jpg",
  "Houston Center for Photography": "museums/hcp.jpg",
  "Lawndale Art Center": "museums/lawndale.jpg",
  "McClain Gallery": "museums/mcclain-gallery.jpg",
  "Menil Drawing Institute": "museums/menil-drawing.jpg",
  "The Health Museum": "museums/health-museum.jpg",
  "The Heritage Society Museum": "museums/heritage-society.jpg",
  "The Houston Fire Museum": "museums/fire-museum.jpg",
  "The Printing Museum": "museums/printing-museum.jpg",
  "Houston Museum of African American Culture": "museums/hmaac.jpg",
  "Houston Police Museum": "museums/police-museum.jpg",
  "Station Museum of Contemporary Art": "museums/station-museum.jpg",
  "TFTI Houston": "museums/tfti.jpg",
  "The Graffiti & Street Art Museum of Texas": "museums/graffiti-museum.jpg",
  "Cullen Sculpture Garden": "museums/cullen-sculpture.jpg",
  "Rienzi": "museums/rienzi.jpg",
  "Museum of Southern History": "museums/southern-history.jpg"
};

// Helper to get image path for a listing
function getListingImage(listing) {
  return imageMap[listing.name] ? 'images/' + imageMap[listing.name] : 'images/logos/Listing-Placeholder.png';
}
